### ISSUE TITLE
After the window is minimized, the window appears black.

### ISSUE THREAD

**Issue by simwangrui** [vsg-dev/VulkanSceneGraph#228] opened 2020-11-27 08:05 UTC
**Describe the bug**
 Run the vsgExample program, minimize the window, the window appears black, no rendering image.
**Desktop 
 - OS: [windows]

**Comment by robertosfield** [comment] 2020-11-27 09:42
Which vsgExample program are you using (there are 30 of them) ?
Which version of Windows?
What hardware, drivers and VulkanSDK version are you using?

If the example supports it could you run the example with -d to enable the Vulkan debug layer to see if there are any Vulkan errors report.

**Comment by simwangrui** [comment] 2020-11-27 11:29
All of example with window,after minimize the window,the window appears black.My OS is windows 10,device is nvidia geforce RTX  2080,driver is 457.09,and vulkan sdk is 1.2.154.1.   I run the example using device nvidia quadro M2000 ,the phenomenon is the same.

**Comment by simwangrui** [comment] 2020-11-27 11:44
I run the example with -d,console output：
Objects: 1
        [0] 0, type: 6, name: NULL
VUID-VkViewport-width-01770(ERROR / SPEC): msgNum: -1542042715 - Validation Error: [ VUID-VkViewport-width-01770 ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xa4164ba5 | vkCreateGraphicsPipelines: pCreateInfos[0].pViewportState->pViewports[0].width (=0.000000) is not greater than 0.0. The Vulkan spec states: width must be greater than 0.0 (https://vulkan.lunarg.com/doc/view/1.2.154.1/windows/1.2-extensions/vkspec.html#VUID-VkViewport-width-01770)
    Objects: 1
        [0] 0, type: 6, name: NULL
VUID-VkViewport-height-01772(ERROR / SPEC): msgNum: -1596201395 - Validation Error: [ VUID-VkViewport-height-01772 ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xa0dbe64d | vkCreateGraphicsPipelines: pCreateInfos[0].pViewportState->pViewports[0].height (=0.000000) is not greater 0.0. The Vulkan spec states: height must be greater than 0.0 (https://vulkan.lunarg.com/doc/view/1.2.154.1/windows/1.2-extensions/vkspec.html#VUID-VkViewport-height-01772)

**Comment by robertosfield** [comment] 2020-11-27 12:24
The vulkan debug errors are really helpful thanks.  I now recall quite a while back discussing with @tomhog about issues with minimizing windows.  It's long enough ago that I don't remember the details.  I think I added some code to handle this case but could only implement it fully under Linux, with some Windows specific work needing to be done to complete it, perhaps Tom never got the chance to complete it before he got swamped with other work.

I will look up the topic to see if I track down what the relevant code is.

**Comment by simwangrui** [comment] 2020-11-27 12:40
Think you very much.Best wishes！

**Comment by robertosfield** [comment] 2020-11-27 17:46
I have started looking into the topic and search for the debug message using google leads us back to an old VSG Issue discussion: #135

**Comment by robertosfield** [comment] 2020-11-28 15:30
Looking at the #135 Issue, which essentially is the same one highlighted in this Issue, @olegded reported the things were working for him and closed it.  I closed the the branch that I made my changes on, not all are present in the current VSG, it looks like a later refactor of the Viewer functionality didn't include some of the workarounds with the minimization issue.  

So we've got a form of regression lurking, but I'm not even sure that it was ever working properly under Windows as the features I added to tackle the issue - the Window::visible() method still exists in VSG master and is implemented in Xcb_Window.cpp but there isn't any implementation of it under Win32 and macOS.  There is also no longer any calls to window->visible() in the Viewer code.

I think the right thing to do is implement the Win32_Window::visible() and macOS_Window::visible() methods and have the Viewer/RecordAndSubmitTasks classes check the window->visible() to prevent any rendering when a window is minimized and not visible.  I can't do the Windows or maxOS dev though, I don't have either system available to test again, and no expertise on either platform.

I will have a look at re-implementing the use of Window::visible() and get this working under Linux.  I'll need help on the other OS's though.

**Comment by robertosfield** [comment] 2020-11-28 15:38
Searching online for hints on what might be need under Windows I came across:

     https://bell0bytes.eu/handling-important-events/

And the official Windows docs on WM_SIZE:

   https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-size

This looks have quite comprehensive handling of minimization etc.

**Comment by robertosfield** [comment] 2020-11-28 17:48
I have had a bash at implementing some code in Win32_Window.cpp to add an Win32_Window::visible() implementation, somewhat along the lines of what works well with Xcb:

    https://github.com/vsg-dev/VulkanSceneGraph/commit/3b92c7023653c1407eb28649f33b390729b44415

The automated builds have passed under Windows so it looks like I haven't broken the build at least.  I don't have any means of testing the runtime.  The changes are checked into a new [Window_Minimized](https://github.com/vsg-dev/VulkanSceneGraph/tree/Window_Minimized) branch.

@simwangrui could you please test to see if minimize and reopening the window works better?

**Comment by simwangrui** [comment] 2020-11-29 07:25
I will be pleased to help with debugging and testing!  I pull the Window_Minimized branch,build this peoject and  vsgExample projects and my own application based vsg. I run the example and my own applichtion with -d one by one. The testing steps and results are as follows:
1.Start the program, the window is in the default size, rendering is ok; after minimizing the window, reopen the window , rendering is also ok.In this case, the issue seems to have been solved.
2.Resize the window,rendering is ok;after minimizing resized window, reopen the window , rendering is also ok.
3.maximize window，rendering is ok;after minimizing maximized window, reopen the window,window appears black,no rendering image. And the console does not output any information.
4.Cancel maximization window down to the origin size,rendering become ok,after minimizing current window,reopen window,rendering is also ok.
Summary：Once the window is maximized,Then minimize this maximized window then the issue arises.

**Comment by robertosfield** [comment] 2020-11-29 08:43
Thanks for the testing.  A bit of progress but something odd still happening for the case:

   maximize window
   minimize, window
   maximize window -> blank screen, but no vulkan debug layer errors.

Perhaps SIZE_RESTORED isn't being generated by Win32 in this case so _windowMapped is remaining false.  I will have a look at the code and and MS docs again to see what might be possible.  Putting a break point in the Win32_Window.cpp code that handle the WM_SIZE to see what the value of wPram is for the above problem sequence would be helpful.  Could you try that are report back what seems to be happening?

**Comment by simwangrui** [comment] 2020-11-29 09:07
Hi ,
Putting a break point in the Win32_Window.cpp that handle the WM_SIZE，the results are as follows:
1.When the window is maximized,  the wParam value is equal SIZE_MAXIMIZED;
2.When the window is minimized，the wParam value is equal SIZE_MINIMIZED;
3.When the window is restored，the wParam value is equal SIZE_RESTORED.

**Comment by robertosfield** [comment] 2020-11-29 09:25
On Sun, 29 Nov 2020 at 09:07, simwangrui <notifications@github.com> wrote:

> Hi ,Putting a break point in the Win32_Window.cpp that handle the
> WM_SIZE，the results are as follows:
> 1.When the window is maximized, the wParam value is equal SIZE_MAXIMIZED;
> 2.When the window is minimized，the wParam value is equal SIZE_MINIMIZED;
> 3.When the window is restored，the wParam value is equal SIZE_RESTORED.
>
Oh dear that squashes my short live theory that perhaps RESTORED wasn't be
called and _windowMapped not being reset to true.

Perhaps a configure event still needs to be generated.  Could you move
the _windowMapped = true into the else block which does the
ConfigureWindowEvent and remove the RESTORED check so for everything other
than the SIZE_MINIMIZED case it sets the _windowMapped and generate thes
the ConfiguewWindowEvent.

Thanks,

**Comment by simwangrui** [comment] 2020-11-29 09:27
Hi,
I try to modify the  process of WM_SIZE code as follow,It's working perfectly now!
`       if (wParam == SIZE_MINIMIZED)
        {
            _windowMapped = false;
        }
        else if (wParam == SIZE_RESTORED || wParam == SIZE_MAXIMIZED)
        {
            _windowMapped = true;
        }
        else
        {
           ......
        }`

**Comment by simwangrui** [comment] 2020-11-29 09:32
Hi,
Sorry,I update my last comment,the origin is not accuracy.
3.When window is not maximized， restored the window，the wParam value is equal SIZE_RESTORED;but When window is maximized,restored the window，the wParam value is equal SIZE_MAXIMIZED.

**Comment by simwangrui** [comment] 2020-11-29 09:43
Hi,
I made such changes as you requested. Now it's working perfectly.Thank you very much!
`case WM_SIZE:
    {
        if (wParam == SIZE_MINIMIZED)
        {
            _windowMapped = false;
        }
        else
        {
            _windowMapped = true;
            _bufferedEvents.emplace_back(new vsg::ConfigureWindowEvent(this, event_time, winx, winy, winw, winh));
        }
        break;
    }`

**Comment by robertosfield** [comment] 2020-11-29 10:54
Thanks for the testing.  Great to hear it's now working.  I'm thinking about adding the logic to account for a window being hidden by another fullscreen window.  I'll add this and roll in with what you have found in testing.

**Comment by robertosfield** [comment] 2020-11-29 12:42
I have had a bash at combining the feedback and adding support for SIZE_MAXHIDE (which should make the application behave like a window has been minimized when it's hidden by another application that goes fullscreen.) 

    https://github.com/vsg-dev/VulkanSceneGraph/commit/6cb4e0036d036cfb0dc660d686919eb98c8d2654

Could you test to see if the minimization works with a maximized and normal window, and also check what happens when you maximize along window.  It might be hard to detect when window to behaving with Window visible set to false - you might spot it on a CPU monitior, failing that adding a debug message into CommandGraph::record(..) or watching the console output when using the Vulkan API layer.

My aim with this change is to lower the CPU load and power consumption when another window gets maximized.

**Comment by simwangrui** [comment] 2020-11-30 05:59
Hi,
I've tested the new commit in Window_Minimized branch.The minimization do works with a maximized and normal window.The test steps are as follows:
1. I setup my first normal window(application based vsg) ,then minimized this window,the cpu load before and after minimization is shown in the figure below.
![1](https://user-images.githubusercontent.com/75113990/100572935-acb5fa80-3311-11eb-92a1-ae5b896035c8.png)
![2](https://user-images.githubusercontent.com/75113990/100573050-e850c480-3311-11eb-8d2c-9667c3c0bd16.png)
2. I setup my second fullscreen window (application based vsg),the cpu load of the first window is shown in the figure below.
![3](https://user-images.githubusercontent.com/75113990/100573470-d6bbec80-3312-11eb-87e1-a91bf3d46096.png)
3. I setup my first window(application based vsg) in debug mode,and hit a break point in the Win32_Window.cpp that handle the WM_SIZE; then I setup the second vsg fullsreen window, unexpect I can not capture any break,and the first window application's cpu load does not decrease.

I also refer to the link document:
SIZE_MAXHIDE : Message is sent to all pop-up windows when some other window is maximized.
[https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-size](url)

First setup normal window application in debug mode, then setup second normal window,after maximized second window,I can not capture any break too.

Is there something wrong with my test case or my window OS settings?

I will be pleased to help with further debugging and testing!

**Comment by robertosfield** [comment] 2020-11-30 09:59
Thanks for the testing.  I wonder if I was being a bit optimistic with the Window manager sending a SIZE_MAXHIDE.  The "send to all pop-up windows" uses the term "pop-up" which makes me wonder if that discounts main widows of applications.

While it would be nice for the SIZE_MAXHIDE to work as I had hoped but it's not a deal breaker like the other bugs so I'll close this Issue.  Thanks for your help in testing.

**Closed by robertosfield** 2020-11-30 09:59 UTC
