### ISSUE TITLE
Trackball ndc coordinate x component's absolute value exceeds 1

### ISSUE THREAD

**Issue by simwangrui** [vsg-dev/VulkanSceneGraph#455] opened 2022-06-04 23:04 UTC
**Describe the bug**
Hi,
`dvec2 Trackball::ndc(PointerEvent& event)
{
    auto renderArea = _camera->getRenderArea();
    auto [x, y] = cameraRenderAreaCoordinates(event);

    double aspectRatio = static_cast<double>(renderArea.extent.width) / static_cast<double>(renderArea.extent.height);
    dvec2 v(
        (renderArea.extent.width > 0) ? (static_cast<double>(x - renderArea.offset.x) / static_cast<double>(renderArea.extent.width) * 2.0 - 1.0) * aspectRatio : 0.0,
        (renderArea.extent.height > 0) ? static_cast<double>(y - renderArea.offset.y) / static_cast<double>(renderArea.extent.height) * 2.0 - 1.0 : 0.0);
    return v;
}`

Does ndc x component need to multiply by aspectRatio？

**Comment by vsg-dev** [comment] 2022-06-05 09:36
I'm perplexed as to what the issue is as NDC above 1.0 is not invalid for this usage case.

The NDC coords used internally by the Tracball and an internal implementation detail, the only thing that matters to the end user is how it behaves.

If there is problem when users are interacting with a view then we can look at this issue.  I'm closing this Issue as it's really just an misunderstanding of how the internals works.

**Closed by vsg-dev** 2022-06-05 09:36 UTC
