### ISSUE TITLE
segmentation falt (core dumped)

### ISSUE THREAD

**Issue by zhangfq-chemistry** [vsg-dev/VulkanSceneGraph#287] opened 2021-06-11 02:24 UTC
vsg has been compiled and install successfully, while most of the examples under vsgExamples/build/bin cannot run with error: segmentation fault (core dumped). The command "ulimit -s 102400" also seems no use.

**Comment by robertosfield** [comment] 2021-06-11 04:45
You are the first to report seg faults so there must be something specific
about your system that is cause the problem, To figure out what it might be
we'll need lots more information.

Could you provide details of the OS, Vulkan SDK, Vulkan drivers, hardware
you are using?

Could you run inside a debugger to get a stack trace.

>

**Comment by rolandhill** [comment] 2021-06-11 06:21
I've successfully used VSG on my desktop for some time now. A while ago I
tried to use it on my laptop and couldn't get it to work because I kept
getting seg faults. I meant to go back and sort it out but haven't had time
to do it yet. I did wonder if it had anything to do with the laptop having
both an integrated Intel graphics card and a dedicated NVidia card - just a
guess. Does the machine you're using have both integrated and dedicated
graphics cards?

Regards,
Roland

**Comment by robertosfield** [comment] 2021-06-11 06:26
Hi Roland,

On Fri, 11 Jun 2021 at 07:21, Roland Hill ***@***.***> wrote:

> I've successfully used VSG on my desktop for some time now. A while ago I
> tried to use it on my laptop and couldn't get it to work because I kept
> getting seg faults. I meant to go back and sort it out but haven't had time
> to do it yet. I did wonder if it had anything to do with the laptop having
> both an integrated Intel graphics card and a dedicated NVidia card - just a
> guess. Does the machine you're using have both integrated and dedicated
> graphics cards?
>

Last month I checked in improvements to the VSG's default device selection
to better handle systems with integrated and dedicated graphics. It would
be worth trying out the VSG on your laptop now.

A crash might be on the VSG side, but could well be or caused by the
driver.  Either way it would be good to get to the bottom of it.  Even if
Vulkan isn't supported we'd want an elegant failure, with an exception
being thrown,

Robert.

**Comment by rolandhill** [comment] 2021-06-11 06:45
Hi Robert,

It's been a long time since I tried and probably before you made those
changes. I'll try and give it a go over the weekend and let you know.

Regards,
Roland

**Comment by robertosfield** [comment] 2021-07-16 21:19
@zhangfq-chemistry could you please answer the questions I've asked above, as there is nothing we can't recreate the issue, or investigate without further information.

**Closed** 2021-07-16 21:20 UTC
