### ISSUE TITLE
Nodes flicker when moving the camera

### ISSUE THREAD

**Issue by sbrkopac** [vsg-dev/VulkanSceneGraph#113] opened 2019-10-29 03:30 UTC
**Describe the bug**
When moving the scene, all nodes in the scene rapidly flicker. There are even some angles or instances where you can get the nodes to disappear completely.

**To Reproduce**

Add the Trackball manipulator to the vsgdraw example

```viewer->addEventHandlers({vsg::CloseHandler::create(viewer), vsg::Trackball::create(camera)});```

**Expected behavior**
No flickering should occur

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Branch: master
 - NVIDIA Driver: 440.98

**Additional context**

**Comment by sbrkopac** [comment] 2019-10-29 03:36
This only seems to happen when I attempt to rotate the scene.

**Comment by robertosfield** [comment] 2019-10-29 09:02
Just tested it and the trackball is not behaving itself at all right now. Clearly there's been a regression due to recent changes to the maths function.  I hope to get a fix checked in this morning.

**Comment by vsg-dev** [comment] 2019-10-29 13:19
I've tracked down the regression to the change in the mat4 constructor order not being taken account of in the lookAtInverse() function.  I've replaced this function with use of the new inverse() function.  An update to VSG master will provide this fix.  The commit is:

https://github.com/vsg-dev/VulkanSceneGraph/commit/3e501385e9fd36010148798b7519d2373f998f95

**Closed by vsg-dev** 2019-10-29 13:19 UTC
