### ISSUE TITLE
Incorrect Keyboard Handling on Windows

### ISSUE THREAD

**Issue by kannode** [vsg-dev/VulkanSceneGraph#669] opened 2022-12-20 02:51 UTC
**Describe the bug**

Keycodes are not mapped correctly. Both Windows Virtual Key (VK) and ASCII (ASCII) codes are used as keys within the _keycodeMap. 
i.e., the map _keycodeMap has the following form, which is likely incorrect as there overlapping key values that map to different semantic keys in VSG.
(VK|ASCII) -> VSG

For example
`
{'p', KEY_p},
{VK_F1, KEY_F1},

both have value 112 for their keys. Since {VK_F1, KEY_F1} appears after {'p', KEY_p} during _keycodeMap initialization, it overwrites {'p',KEY_p}. Hence it is unclear what should happen.

**To Reproduce**
1. Execute vsginput
2. Press the key corresponding to 'P' on the keyboard. (do not use the shift or caps lock key, just hit the 'p' key).
3. We get the following keycode  (see screenshot)
<img width="766" alt="issue" src="https://user-images.githubusercontent.com/32265121/208569968-24ff5566-328b-4bf7-b462-a9f720f89e2b.PNG">

**Expected behavior**
keyBase='P', keyModified='p'.
the virtual key 'P' is pressed and since there are no modifiers, key modified should be 'p'.

**Comment by robertosfield** [comment] 2022-12-20 09:02
*Expected behavior*

> keyBase='P', keyModified='p'.
> the virtual key 'P' is pressed and since there are no modifiers, key
> modified should be 'p'.
>
> That is the behavior what you are expecting for whatever reason, but it's
not the intended behavior.

p is the unmodified base, when the shift modifier or caps lock modifier is
applied you get a P.

It makes little sense to have a "modified key" from P to p when no modifier
is pressed, and P to P when the modifier is pressed.

**Comment by robertosfield** [comment] 2022-12-20 09:05
Now if on Windows you are indeed seeing a base key of 'p' and modified key
of 'P' when no caps or shift key is applied then this is a bug.

The capitalization of the physical keyboard is something that dates back to
typewriters and should not be taken as the meaning of an unmodified key.

**Comment by robertosfield** [comment] 2022-12-20 09:17
@kannode  If you have a linux system available then it would be useful to use it as the reference for intended behavior.

I wrote the original implementation and Xcb_Window.cpp  then Windows implementation was made afterwards by @tomhog.  I don't have Window systems to test against so haven't been able to QA the Windows side, and have to rely upon the community to help support the Windows side.

As a general comment, the VSG convention is consistent with the one used in the OSG, which itself is consistent with X11.  From the sound of it there may be an implementation issue under Windows w.r.t this convention.

**Comment by kannode** [comment] 2022-12-20 19:29
I'll take a look at linux vsg for reference behavior and implementation and resubmit a pr for review.

**Comment by robertosfield** [comment] 2022-12-20 19:39
On Tue, 20 Dec 2022 at 19:30, Suresh Kannan ***@***.***>
wrote:

> I'll take a look at linux vsg for reference behavior and implementation
> and resubmit a pr for review.
>

Thanks,

**Comment by kannode** [comment] 2023-01-06 14:37
Robert, Not yet. But I should make progress by Monday as I am working on client work at the moment.

**Comment by robertosfield** [comment] 2023-01-11 10:01
Thanks to @kannode improvements to Win32_Window we can close this issue :-)

**Closed by robertosfield** 2023-01-11 10:01 UTC
