### ISSUE TITLE
Does not install

### ISSUE THREAD

**Issue by timprepscius** [vsg-dev/VulkanSceneGraph#88] opened 2019-07-22 20:34 UTC
Greetings,

Could you create a full install script on osx- which is known to work and does everything, and tested on a clean system?

I am getting an error with cmake generating makefiles, and I could spend time on here or some forum posting outputs and trying new things, blah-be-de-blah-blah, wasting a lot of time of multiple people.

But actually, it seems to me that the problem actually is that there is not install script known to work.  I really should be able to download some file, and type "./install-vsg"

Thanks, this would undoubtedly help many people besides myself, and should be considered part of maintaining a library you wish people to use.

**Comment by sbrkopac** [comment] 2019-07-22 21:17
`Could you create a full install script on osx- which is known to work and does everything, and tested on a clean system?`

CMake should be generating the install scripts.

`I am getting an error with cmake generating makefiles, and I could spend time on here or some forum posting outputs and trying new things, blah-be-de-blah-blah, wasting a lot of time of multiple people.`

You'd rather waste people's time by rolling out a custom install script?

`But actually, it seems to me that the problem actually is that there is not install script known to work. I really should be able to download some file, and type "./install-vsg"`

And when that breaks? Are you going to report the errors?

`Thanks, this would undoubtedly help many people besides myself, and should be considered part of maintaining a library you wish people to use.`

Install scripts work on both windows and linux. If there is an issue with the osx generation of the build / install files, you should post the logs accordingly.

**Comment by timprepscius** [comment] 2019-07-22 22:09
> And when that breaks? Are you going to report the errors?

Well, in theory, you would test this. ;-)
https://medium.com/@twister.mr/installing-macos-to-virtualbox-1fcc5cf22801

If I had a script which was known to work, I could easily find out what is differing from my environment and the test environment.

But since there is no-known-working-script, I have to guess.  And I have no idea whether anyone has actually tested that the current master works or not.  What if it "just doesn't work."  That will be hours and hours lost, because I will have no way of knowing.

So, yeah.  A install script which is known to work on an osx image with the current xcode installed, would be great.

**Comment by vsg-dev** [comment] 2019-07-23 07:43
The VSG uses modern CMake install support, It should be simply be a case of build the VSG and run make install. If there are errors with this then please be specific in what they are.

The use of CMake helps avoid the project being overburdened with platforms specific "solutions", something I'm keen to maintain. The VSG is a constantly evolving at this point, having CMake enables us to make changes and maximize that changes I do under Linux don't break the build under Windows, OSX etc.  Issues still do arise, when they do either reporting the issue here or generating a PR to fix the issue is the way that's worked well so far.

However, we can't fix issues when we don't get a specific description of the problem.  At this point I don't know if it's a technical problem you the CMake build scripts that can't handle you specific OSX setup, or that you haven't read and followed the instructions, or whether the instructions aren't yet easy enough to follow.

**Comment by timprepscius** [comment] 2019-07-23 14:59
Yeah, I understand CMake.

What I'm saying, is that you need a testing environment for your project.
You need a replicatable testing environment.

For instance, you have a virtual machine with OSX on it.
You have a script which:
1. installs xcode, (one line)
2. downloads Vulkan and installs to local, or sets up environment variables, etc
3. git clones your repository
4. runs a cmake creating xcode, and compile the xcode project.
5. runs some test.

In this way, as I said previously, I could find the difference between my environment and yours.
Right now I'm getting CMake errors.  I have a working vulkan install.  This leads me to think that your github repo doesn't work with OSX as of the moment, or the instructions were incomplete.

In both cases, having the setup I described would allow me to fix things in less than 30 minutes.
If I post bugs and people ponder on what they might be, it will be much more time.

**Comment by vsg-dev** [comment] 2019-07-23 16:49
We aren't about to start trying to implement such a script just to appease your particular preferred workflow.  Writing, testing, debugging and maintain such a script won't actually resolve any of the immediate problems.  If you think such a script is so useful then you'll need to scratch the itch and come up with it and be prepared to maintain it as we have lots of other work to get on with.

What we can do right now is try to do is address the problems that you have come across with the existing build system.  Two of us have asked you for this info but as yet we sit it frustrated by lack of anything to go on what to resolve.  All we know is you have some unspecified problem, with some unspecified version of CMake/Vulkan/C++ tools.

If you can't provide this information then I have no other option than to close this Issue as there is nothing we can do to resolve the problems.

**Comment by timprepscius** [comment] 2019-07-23 17:07
Fair enough.  Nobody wants to write testers.  I understand that.  Testers are useless anyhow, right ;-)

**Comment by vsg-dev** [comment] 2019-07-23 17:16
Please, just answer the questions about what went wrong so we can try to fix it.

**Comment by vsg-dev** [comment] 2019-07-27 15:45
I'm closing is "Issue" as it doesn't actually explain any issues with the actual code, just declares a personal feature request.

**Closed by vsg-dev** 2019-07-27 15:45 UTC
