### ISSUE TITLE
problem about update uniform buffer

### ISSUE THREAD

**Issue by HowellDong** [vsg-dev/VulkanSceneGraph#688] opened 2023-01-12 02:48 UTC
`BufferInfo` do not use staging buffer (it is right for uniform buffer),  but `TransferTask`  use staging buffer to update a host visible buffer.

**Comment by robertosfield** [comment] 2023-01-12 08:42
It looks like you are over complicating things. Have a look at the vs
dynamicvertex example:

https://github.com/vsg-dev/vsgExamples/blob/master/examples/state/vsgdynamicvertex/vsgdynamicvertex.cpp

The key parts are to set the data->properties.dataVariance to DYNAMC_DATA
prior to calling viewer.compile() and to call data->dirty() after you've
updated the data.

This mechanism works for textures, uniform data and vertex data.

There are also other vsgExamples that illustrate this mechanism:

/Dev/vsgExamples/examples$ grep -r DYNAMIC .
./state/vsgdynamictexture_cs/vsgdynamictexture_cs.cpp:
   textureData->properties.dataVariance = vsg::DYNAMIC_DATA;
./state/vsgdynamicvertex/vsgdynamicvertex.cpp:
               vertices->properties.dataVariance = lateTransfer ? vsg::
DYNAMIC_DATA
_TRANSFER_AFTER_RECORD : vsg::DYNAMIC_DATA;
./state/vsgcomputevertex/vsgcomputevertex.cpp:
   computeScale->properties.dataVariance = vsg::DYNAMIC_DATA;
./state/vsgclip/vsgclip.cpp:
       eyeClipSettings->properties.dataVariance = vsg::DYNAMIC_DATA;
./state/vsgdynamictexture/vsgdynamictexture.cpp:
   textureData->properties.dataVariance = lateTransfer ? vsg::DYNAMIC
_DATA_TRANSF
ER_AFTER_RECORD : vsg::DYNAMIC_DATA;
./state/vsgtexturearray/vsgtexturearray.cpp:        if (update)
textureData->properties.dataVariance = vsg::DYNAMIC_DATA;

**Comment by HowellDong** [comment] 2023-01-12 10:05
My point is it is not necessary for `TransferTask` using staging buffer(host visible) to update a host visible buffer(DescriptorBuffer).  

> It looks like you are over complicating things. Have a look at the vs dynamicvertex example: https://github.com/vsg-dev/vsgExamples/blob/master/examples/state/vsgdynamicvertex/vsgdynamicvertex.cpp The key parts are to set the data->properties.dataVariance to DYNAMC_DATA prior to calling viewer.compile() and to call data->dirty() after you've updated the data. This mechanism works for textures, uniform data and vertex data. There are also other vsgExamples that illustrate this mechanism: /Dev/vsgExamples/examples$ grep -r DYNAMIC . ./state/vsgdynamictexture_cs/vsgdynamictexture_cs.cpp: textureData->properties.dataVariance = vsg::DYNAMIC_DATA; ./state/vsgdynamicvertex/vsgdynamicvertex.cpp: vertices->properties.dataVariance = lateTransfer ? vsg:: DYNAMIC_DATA _TRANSFER_AFTER_RECORD : vsg::DYNAMIC_DATA; ./state/vsgcomputevertex/vsgcomputevertex.cpp: computeScale->properties.dataVariance = vsg::DYNAMIC_DATA; ./state/vsgclip/vsgclip.cpp: eyeClipSettings->properties.dataVariance = vsg::DYNAMIC_DATA; ./state/vsgdynamictexture/vsgdynamictexture.cpp: textureData->properties.dataVariance = lateTransfer ? vsg::DYNAMIC _DATA_TRANSF ER_AFTER_RECORD : vsg::DYNAMIC_DATA; ./state/vsgtexturearray/vsgtexturearray.cpp: if (update) textureData->properties.dataVariance = vsg::DYNAMIC_DATA;

**Comment by robertosfield** [comment] 2023-01-12 10:59
I'm confused by what you now mean, what the issue is.

vsg::TransferData uses a staging buffer, not just for the Vulkan requirement of using a staging buffer for passing data to GPU local memory but also to multi-buffer the data to avoid CPU updates for the current frame being recorded affecting frame that is being rendered on the GPU.  TransferData also enables batch copying and avoid the expensive mapping/unmapping of the memory.

You can if your want role you own transfer of data but it's a lot more complicated and typically slower.  I wrote TransferData and the VSG mechanism for updating data to make users lives easier and to help their applications perform better.

I'm closing this Issue as there isn't an issue being described.

**Closed by robertosfield** 2023-01-12 10:59 UTC
