### ISSUE TITLE
Resizing the window on Ubuntu issue

### ISSUE THREAD

**Issue by spezialspezial** [vsg-dev/VulkanSceneGraph#406] opened 2022-02-23 16:01 UTC
First let me say that this project is really cool. I saw the paging youtube videos and started installing right away. But now for something different:

**Describe the bug**
All Examples and MyFirstVsgApplication disappear when resizing the window on Ubuntu, vsgQt shows uninitialized memory jazz in the new window region and hangs. GDB reports nothing.

**To Reproduce**
- Build VulkanSceneGraph following instructions.
- Start example: vsgviewer models/teapot.vsgt
- Grab corner of window and resize.
- App closes and process disappears.

**Desktop:**
 - Ubuntu 20.04.3 LTS, 5.13.0-30-generic, Desktop x86_64, AMD RX 580, 1.3.204.0~rc1-1lunarg20.04-1, amdvlk64.so 1.2.197 from amdgpu 21.50.50000-1
 - VulkanSceneGraph b83998efec73f4418b06deee123cd69172bcfb7b (18.02.2022)

Any hint how to narrow this down?

**Comment by robertosfield** [comment] 2022-02-23 16:40
My desktop system has Ubuntu 21.04 with NVidia 2060 and don't see a problem with resizing.  I also have Xubuntu 18.04, and Kubuntu 20.04 installed and again resizing works fine.  It also works fine with multiple NVidia 1650 cards when I do multi GPU.

However, I recently upgraded my Intel laptop from 21.04 where resizing worked to 21.10 and resizing has stopped working - it doesn't crash, only the viewport doesn't update.  I haven't had a chance to figure out what is wrong.  My guess is that is driver issue handling Xcb/Vulkan window integration with Wayland.  

Perhaps you are seeing something similar - a driver bug that isn't handling Xcb/Vulkan correctly.  I have intended to buy an AMD card to test against but current Gfx cards are either out of stock or massively over priced so have held off.

**Comment by robertosfield** [comment] 2022-02-23 17:51
On Wed, 23 Feb 2022 at 17:34, spezialspezial ***@***.***>
wrote:

> Hi, thanks for getting back.
>
> I can not reproduce this issue with the Khronos Vulkan-Samples so far. I
> will look for a way to dump some info about the selected device, maybe it
> gives some pointers.
>
That's useful to know.  If we can uncover what is going on the VSG side it
might be helpful to find a 3rd party sample that is similar to a VSG
example that both doing similar things, then capture the Vulkan API debug
layout output and compare what both are doing.

> 'but current Gfx cards are either out of stock or massively over priced so
> have held off.'
> Tell me about it. The 580 was planned as the temporary interim solution.
> Hopefully the rumors about changes soon are true.
>
> Do you have any other hardware/OS combinations you can test against?

Another test worth doing is to try a VSG commit prior to this commit:


https://github.com/vsg-dev/VulkanSceneGraph/commit/8a37810a2ccd9bcfe543f191573cfc7a75fd7e3d

This commit implements reuse of vkRendassPass resources when resizing a
vsg::Window, this is more efficient that just creating an entirely new
RenderPass each window resize, but perhaps might be something badly
implemented on your drivers.

Perhaps try df8b21515e95b9f2171235434b8577adc7dc9935 to see if that works
better. If so this will give us something to look into.

**Comment by spezialspezial** [comment] 2022-02-23 18:58
- vsg does select the most reasonable device, not Mesa CPU or similar. 
- no change with 8a37810a2ccd9bcfe543f191573cfc7a75fd7e3d
- I do get a warning : window->acquireNextImage() VkResult = 1000001003 translating to -> Provided by VK_KHR_swapchain VK_SUBOPTIMAL_KHR = 1000001003

**Comment by robertosfield** [comment] 2022-02-23 20:17
On Wed, 23 Feb 2022 at 18:58, spezialspezial ***@***.***>
wrote:

>
>    - vsg does select the most reasonable device, not Mesa CPU or similar.
>    - no change with 8a37810
>    <https://github.com/vsg-dev/VulkanSceneGraph/commit/8a37810a2ccd9bcfe543f191573cfc7a75fd7e3d>
>    - I do get a warning : window->acquireNextImage() VkResult =
>    1000001003 translating to -> Provided by VK_KHR_swapchain VK_SUBOPTIMAL_KHR
>    = 1000001003
>
> My best guess is the AMD driver has some constraints on how to set things
up to keep it happy.  I'm not see any Vulkan debug layer errors when
resizing so the Vukan debug layer doesn't see any invalid in the settings
the VSG is using.

Without AMD graphics hardware to test against (I have an AMD CPU on this
desktop, but alas no integrated graphics) that it's much I can do at this
point.  There is a chance others in the VSG community have tried out AMD
graphics and might have insights, posting on vsg-users
<https://groups.google.com/g/vsg-users> an explanation of the issues you've
seen might pull in some insights.

**Comment by spezialspezial** [comment] 2022-02-23 20:39
Yeah, another AMD user to test this would be handy right now. There must be dozends out there.

**Comment by spezialspezial** [comment] 2022-02-24 00:12
Not really a fix but crashing stops if I force a rebuild of the swapchain in Viewer::acquireNextFrame() on result == VK_SUBOPTIMAL_KHR

**Comment by robertosfield** [comment] 2022-02-24 06:51
On Thu, 24 Feb 2022 at 00:12, spezialspezial ***@***.***>
wrote:

> Not really a fix but crashing stops if I force a rebuild of the swapchain
> in Viewer::acquireNextFrame() on result == VK_SUBOPTIMAL_KHR
>
>
How does it perform when you do that?  How often does the VK_SUBOPTIMAL_KHR
get generated?

**Comment by spezialspezial** [comment] 2022-02-24 14:06
> How does it perform when you do that?

I'm getting this:
 
XCB spams XCB_GE_GENERIC event after Vulkan window resize
https://bugs.freedesktop.org/show_bug.cgi?id=99263

a lot and at least a very long time after stopping to resize but with device/driver:

Api Version: 1.2.197
Driver Version: 2.0.3.15
Vendor ID: AMD
Device Type: DISCRETE GPU
Device Name: Radeon RX 580 Series

if I add a case in Xcb_Window to quiet the notification flood I can see some occasional

VUID-VkRenderPassBeginInfo-renderArea-02849(ERROR / SPEC): msgNum: -1280461305 - Validation Error: [ VUID-VkRenderPassBeginInfo-renderArea-02849 ] Object 0: handle = 0xfab64d0000000002, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0xb3adb607 | vkCmdBeginRenderPass: Cannot execute a render pass with renderArea not within the bound of the framebuffer, renderArea.offset.y (0) + renderArea.extent.height (716) is greater than framebuffer height (712). The Vulkan spec states: renderArea.offset.y + renderArea.extent.height must be less than or equal to VkFramebufferCreateInfo::height the framebuffer was created with (https://vulkan.lunarg.com/doc/view/1.3.204.0/linux/1.3-extensions/vkspec.html#VUID-VkRenderPassBeginInfo-renderArea-02849)
    Objects: 1
        [0] 0xfab64d0000000002, type: 18, name: NULL
        
        
The window does strongly flicker during resize, sometimes shows memory jazz but no hang.


>How often does the VK_SUBOPTIMAL_KHR get generated?

VK_SUBOPTIMAL_KHR gets emitted regularily during resize

**Comment by robertosfield** [comment] 2022-02-24 14:44
Thanks for persevering. I'm not familiar with XCB_GE_GENERIC and
the xcb_ge_generic_event_t that it's associated with.  I wrote the
Xcb_Window.cpp but didn't come across XCB_GE_GENERIC.  How did you figure
out that this was being generated in your case?

The Validation Error suggests to me that the window has changed size after
the render pass dimensions have been updated. If you are continuously
dragging then potentially the window manager could cause this by changing
the window size quicker than you can keep track of it, I've hit upon this
issue before so have had to refine the Window resize handle but for you
dirver combination it now looks like it isn't sufficient.

Does the VK_SUBOPTIMAL_KHR happen at the same time as the Validation Error?

FYI, on my system I don't ever see flickering or off odd output.

Do you know if the Vulkan samples use Xcb as well?  Does they show any of
the same glitches you are seeing with VSG applications?

**Comment by robertosfield** [comment] 2022-02-24 16:28
On Thu, 24 Feb 2022 at 15:28, spezialspezial ***@***.***>
wrote:

> How did you figure out that this was being generated in your case?
>
> It was logging the equivalent int value and I was doing a full text search
> on the sources. It's very prominent as there is a *lot* of events
> generated.
>
Do you have a branch of the VSG with these changes?  Once I get a chance to
do some testing it would be useful to have a look at what changes you've
done to tease out what's happening.



> VK_SUBOPTIMAL_KHR is emitted consistently during resize. Validation error
> appears just sporadically with no regular pattern, timing related I'd
> suppose.
>
> Do you know if the Vulkan samples use Xcb as well?
> Not sure right now.
>
> Does they show any of the same glitches
> Slightly heavy/choppy/laggy compared to vanilla windows but no glitches at
> all.
>
>
I guess this is encouraging - it should be possible to improve things.

> Is there an easy way to choose the selected device? I should have the
> choice of opensource and pro variant flavour of amdgpu vulkan. Might give
> some more insight.
>
The vsgdeviceselection example illustrates how you can specify the device
that the VSG uses when creating a window.  I wrote up details on this
example on vsg-users last year:

    https://groups.google.com/g/vsg-users/c/fFgChgoqM3w/m/1x6TcHxoDQAJ

I will have another look at buying a AMD card, as I don't think I'll be
able to avoid needing it prior to 1.0, these types of issues have to be
resolved or at least understood if does just come down to driver bugs that
folks have to workaround.

**Comment by spezialspezial** [comment] 2022-02-24 16:57
> Do you know if the Vulkan samples use Xcb as well?

Regarding Xcb, this is the relevant portion from Vulkan-Samples:

```
#	elif defined(VK_USE_PLATFORM_XCB_KHR) || defined(VK_USE_PLATFORM_XLIB_KHR) || defined(VK_USE_PLATFORM_WAYLAND_KHR)
	vkb::UnixPlatform platform{vkb::UnixType::Linux, argc, argv};
#	endif
```

**Comment by spezialspezial** [comment] 2022-02-24 17:01
> I will have another look at buying a AMD card

I can lend you mine in a couple of days.

**Comment by spezialspezial** [comment] 2022-02-24 17:06
> The vsgdeviceselection example illustrates how you can specify the device that the VSG uses

Thanks, I'll check it out.

**Comment by robertosfield** [comment] 2022-02-24 17:10
On Thu, 24 Feb 2022 at 17:02, spezialspezial ***@***.***>
wrote:

> I will have another look at buying a AMD card
>
> I can lend you mine in a couple of days.
>
> Thanks, but it's probably best for me to get one for testing long term.
One option might be to upgrade my AMD2700 CPU to a more recent AMD chip
with integrated graphics as it's not a huge amount more than a dedicated
GPU.  I'd hope there wouldn't be a behavioral difference between integrated
and discrete AMD GPUs.

**Comment by spezialspezial** [comment] 2022-02-24 18:02
> Do you have a branch of the VSG with these changes?

I didn't do a lot to the sources. Basically just just adding a case for VK_SUBOPTIMAL_KHR

[Viewer.diff.txt](https://github.com/vsg-dev/VulkanSceneGraph/files/8134737/Viewer.diff.txt)

**Comment by robertosfield** [comment] 2022-03-09 20:46
Cool.  I'll try it out when I get my to my desktop system tomorrow.  FIrst
I'll test under Ubuntu 21.04 on Nvidia and 21.10 on Intel laptop and then
later in the day on AMD 5700G's embedded graphics as I'll be updating my
desktop tomorrow to enable me to test both AMD and NVidia on one system -
if drivers let me play.

**Comment by robertosfield** [comment] 2022-03-10 08:35
@liliolett I've just done a quick test of your changes on my Ubuntu21.04 + Geforce system and window resizing is working fine and no Vulkan debug errors are reported when running vsgviewer with -d.  A code review of both your recent commits suggests that changes are sound so I've generated a pull request #416 here on vsg-dev/VulkanSceneGraph.

I will check out this as a branch on my Intel laptop to see whether it helps with the problems in resize I've seen since upgraded from Ubuntu 21.04 to 21.10.   Fingers crossed.

**Comment by vsg-dev** [comment] 2022-03-10 10:12
I've tested @liliolett changes on my Intel laptop and it fixes the resize regression I saw on upgrading to Ubuntu 21.10 and works seamlessly on my AMD2700+Geforce2060 desktop system so have gone ahead and merged these changes with VSG master.

@spezialspezial could you test out VSG master and see if it fixes the resize issues?

**Comment by spezialspezial** [comment] 2022-03-13 20:20
> @spezialspezial: Could you try if [my fork](https://github.com/liliolett/VulkanSceneGraph) works for you as well?

@liliolett 

Sorry, took me a bit as I swapped cards in the meantime and I had to prep an old box first.

So, with Ubuntu 18 and vanilla amdgpu and vulkan driver from the repositories I can reproduce the error on the master branch and can confirm smooth resizing using your branch. Nice!

**Comment by spezialspezial** [comment] 2022-03-13 20:27
> @spezialspezial could you test out VSG master and see if it fixes the resize issues?

Yes, newest master works too.

**Comment by vsg-dev** [comment] 2022-03-13 22:16
Thanks for the testing, good to hear it's working fine,

**Closed by vsg-dev** 2022-03-13 22:16 UTC
