### ISSUE TITLE
Jittering shadows in vsgshadow

### ISSUE THREAD

**Issue by rolandhill** [vsg-dev/VulkanSceneGraph#1028] opened 2023-11-16 23:57 UTC
Hi Robert,

I just pulled a fresh copy of all the VSG libraries and vsgExamples to try vsgshadow (VSG commit ca7b190db9066960ae3b136c33540d1aa50d88f9). The image initially displays OK, but if I spin it at all the shadows jitter and the white plane flashes black. If I stop moving the mouse it all looks good again, so I can't get a screen shot.

Is it working for you? I'm using Kubuntu 22.04, an Nvidia 3070Ti and the latest Vulkan drivers 1.3.268.0 (I also used 1.3.250.1).

Regards,
Roland

**Comment by robertosfield** [comment] 2023-11-17 08:37
I have just update my Intel Ubuntu 22.04 laptop to the VSG/vsgExamples Shadows branch latest and rebuild everything and it so far it all looks fine.  Running with -d doesn't reveal any Vulkan debug layer errors.

I will next try my AMD5700G desktop system.

Could you try running with -d to see if any issues are picked up.

**Comment by robertosfield** [comment] 2023-11-17 08:57
Everything looks solid on my desktop system with AMD5700G with the latest Shadows branch.  Now debug errors reported when using -d.

@rolandhill has this jittering issue recently appeared?  Could a driver update caused a problem?

**Comment by rolandhill** [comment] 2023-11-19 22:01
Hi Robert,

Running with -d does not produce any extra output.

This is the first time that I've tried vsgshadow, so I don't know if
the problem has just appeared. If it's working there on much the same
setup, then it sounds like it's something I've done. I'll manually clean
out all my vsg components, update everything and try again.

I'm using the Nvidia custom driver for Kubuntu. It's just the standard one
(currently 525.147.05) that gets installed when you enable custom drivers.

I'll let you know how it goes.

Cheers,
Roland

**Comment by robertosfield** [comment] 2023-11-19 23:04
If Vulkan debug layer isn't producing errors then we don't have any obvious leads.

I don't have my NVIdia card in my desktop system during the shadow development so I can try it out tomorrow and see what happens.

**Comment by rolandhill** [comment] 2023-11-20 01:12
I deleted all related files from /usr/local, pulled updated VSG and rebuilt everything. Still the same result and nothing generated using -d. A short video is attached.

Cheers,
Roland



https://github.com/vsg-dev/VulkanSceneGraph/assets/2024003/81cd5558-2c7b-40e7-9d05-973c9be629f2

**Comment by robertosfield** [comment] 2023-11-20 12:42
Thanks for the video.  

I have installed my Geforce 2060 on my Kubuntu 22.04 system and my initial tests show that it's working correctly, however, it's using the Mesa LLVMPIPE driver for now.

~~~ sh
$ vsgdeviceselection --list
vkEnumerateInstanceVersion() 4206860
VK_API_VERSION = 1.3.268.0

physicalDevices.size() = 1
    matched ref_ptr<vsg::PhysicalDevice>(vsg::PhysicalDevice 0x7ffa46e7bc38) llvmpipe (LLVM 15.0.7, 256 bits), deviceType = 4, apiVersion = 1.3.238, driverVersion = 0.0.1
    QueueFamilyProperties 1
        VkQueueFamilyProperties[0] queueFlags = GRAPHICS | COMPUTE | TRANSFER, queueCount = 1, timestampValidBits = 64, minImageTransferGranularity = {1, 1, 1}
~~~

I will install the NVidia drivers next and see if I can reproduce the issues you are seeing.

**Comment by timoore** [comment] 2023-11-20 13:33
Try enabling the synchronization layer, although it may be hard to pick out the shadow problems.

There is only one copy of each shadow cascade image, right?

In ViewDependentState.cpp, you could try inserting another barrier in front of the shadow passes with src = VK_ACCESS_SHADER_READ_BIT, dest=VK_ACCESS_DEPTH_ATTACHMENT_WRITE_BIT

**Comment by robertosfield** [comment] 2023-11-20 13:57
At a test of the synchronization hypothesis I added a:

    viewer->waitForFences(0, waitTimeout);

To the vsgshadow.cpp main frame loop and it fixes the issue as far as I can tell.  This puts a big barrier in the frame so isn't an actual fix but does indicate it's a across frame boundary issue rather than an synchronization issue that is happening within a single frame.

My best guess is that the shadow map render texture is being written to by the new frame while the previous frame is still reading from it.  If this is the case then this suggest the NVidia driver is super keen to just get on with rendering the next frame as quickly as possible and with need an explicit barrier before we start writing to the shadow map textures so that the previous frame has fully finished reading from it.

**Comment by robertosfield** [comment] 2023-11-20 14:49
I added support for enabling the Vulkan synchronization layer to vsgshadow example but this didn't highlight any problems so I then tried vkconfig and enabled the synchronization layer and this didn't reveal any problems but then I enabled an ALPHA feature associated with the synchronization layer and bingo I've got errors of the form:

~~~ sh
Launching Vulkan Application:
- Layers overridden by "Synchronization" configuration.
- Application: vkcube
- Executable: /home/robert/Dev/vsgExamples/bin/vsgshadow
- Working Directory: /home/robert/Dev/vsgExamples/data
- Command-line Arguments: -f 2
- Log file: /home/robert/Dev/vsgExamples/vsgshadow.txt

info: createTestScene() extents = 
    -0.5 -0.5 -1
    4.99829 0.5 1


UNASSIGNED-CreateInstance-status-message(INFO / SPEC): msgNum: -2016116905 - Validation Information: [ UNASSIGNED-CreateInstance-status-message ] Object 0: handle = 0x562dfb1624b0, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x87d47f57 | vkCreateInstance():  Khronos Validation Layer Active:
    Settings File: Found at /home/robert/.local/share/vulkan/settings.d/vk_layer_settings.txt specified by VkConfig application override.
    Current Enables: VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION, VALIDATION_CHECK_ENABLE_SYNCHRONIZATION_VALIDATION_QUEUE_SUBMIT.
    Current Disables: None.

    Objects: 1
        [0] 0x562dfb1624b0, type: 1, name: NULL

SYNC-HAZARD-WRITE-RACING-WRITE(ERROR / SPEC): msgNum: 1950113897 - Validation Error: [ SYNC-HAZARD-WRITE-RACING-WRITE ] Object 0: handle = 0x562dfce21d10, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x743c6069 | vkQueueSubmit():  Hazard WRITE_RACING_WRITE for entry 0, VkCommandBuffer 0x562dfd2fdd00[], Recorded access info (recorded_usage: SYNC_COPY_TRANSFER_WRITE, command: vkCmdCopyBuffer, seq_no: 1, reset_no: 1). Access info (prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: SYNC_DRAW_INDIRECT_INDIRECT_COMMAND_READ|SYNC_DRAW_INDIRECT_TRANSFORM_FEEDBACK_COUNTER_READ_EXT|SYNC_VERTEX_SHADER_ACCELERATION_STRUCTURE_READ|SYNC_VERTEX_SHADER_DESCRIPTOR_BUFFER_READ_EXT|SYNC_VERTEX_SHADER_SHADER_BINDING_TABLE_READ|SYNC_VERTEX_SHADER_SHADER_SAMPLED_READ|SYNC_VERTEX_SHADER_SHADER_STORAGE_READ|SYNC_VERTEX_SHADER_SHADER_STORAGE_WRITE|SYNC_VERTEX_SHADER_UNIFORM_READ|SYNC_TESSELLATION_CONTROL_SHADER_ACCELERATION_STRUCTURE_READ|SYNC_TESSELLATION_CONTROL_SHADER_DESCRIPTOR_BUFFER_READ_EXT|SYNC_TESSELLATION_CONTROL_SHADER_SHADER_BINDING_TABLE_READ|SYNC_TESSELLATION_CONTROL_SHADER_SHADER_SAMPLED_READ|SYNC_TESSELLATION_CONTROL_SHADER_SHADER_STORAGE_READ|SYNC_TESSELLATION_CONTROL_SHADER_SHADER_STORAGE_WRITE|SYNC_TESSELLATION_CONTROL_SHADER_UNIFORM_READ|SYNC_TESSELLATION_EVALUATION_SHADER_ACCELERATION_STRUCTURE_READ|SYNC_TESSELLATION_EVALUATION_SHADER_DESCRIPTOR_BUFFER_READ_EXT|SYNC_TESSELLATION_EVALUATION_SHADER_SHADER_BINDING_TABLE_READ|SYNC_TESSELLATION_EVALUATION_SHADER_SHADER_SAMPLED_READ|SYNC_TESSELLATION_EVALUATION_SHADER_SHADER_STORAGE_READ|SYNC_TESSELLATION_EVALUATION_SHADER_SHADER_STORAGE_WRITE|SYNC_TESSELLATION_EVALUATION_SHADER_UNIFORM_READ|SYNC_GEOMETRY_SHADER_ACCELERATION_STRUCTURE_READ|SYNC_GEOMETRY_SHADER_DESCRIPTOR_BUFFER_READ_EXT|SYNC_GEOMETRY_SHADER_SHADER_BINDING_TABLE_READ|SYNC_GEOMETRY_SHADER_SHADER_SAMPLED_READ|SYNC_GEOMETRY_SHADER_SHADER_STORAGE_READ|SYNC_GEOMETRY_SHADER_SHADER_STORAGE_WRITE|SYNC_GEOMETRY_SHADER_UNIFORM_READ|SYNC_FRAGMENT_SHADER_ACCELERATION_STRUCTURE_READ|SYNC_FRAGMENT_SHADER_COLOR_ATTACHMENT_READ|SYNC_FRAGMENT_SHADER_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_FRAGMENT_SHADER_DESCRIPTOR_BUFFER_READ_EXT|SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ|SYNC_FRAGMENT_SHADER_SHADER_BINDING_TABLE_READ|SYNC_FRAGMENT_SHADER_SHADER_SAMPLED_READ|SYNC_FRAGMENT_SHADER_SHADER_STORAGE_READ|SYNC_FRAGMENT_SHADER_SHADER_STORAGE_WRITE|SYNC_FRAGMENT_SHADER_UNIFORM_READ|SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_EARLY_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE|SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_READ|SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE|SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ|SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_READ_NONCOHERENT_EXT|SYNC_COLOR_ATTACHMENT_OUTPUT_COLOR_ATTACHMENT_WRITE|SYNC_COMPUTE_SHADER_ACCELERATION_STRUCTURE_READ|SYNC_COMPUTE_SHADER_DESCRIPTOR_BUFFER_READ_EXT|SYNC_COMPUTE_SHADER_SHADER_BINDING_TABLE_READ|SYNC_COMPUTE_SHADER_SHADER_SAMPLED_READ|SYNC_COMPUTE_SHADER_SHADER_STORAGE_READ|SYNC_COMPUTE_SHADER_SHADER_STORAGE_WRITE|SYNC_COMPUTE_SHADER_UNIFORM_READ|SYNC_HOST_HOST_READ|SYNC_HOST_HOST_WRITE|SYNC_COMMAND_PREPROCESS_NV_COMMAND_PREPROCESS_READ_NV|SYNC_COMMAND_PREPROCESS_NV_COMMAND_PREPROCESS_WRITE_NV|SYNC_CONDITIONAL_RENDERING_EXT_CONDITIONAL_RENDERING_READ_EXT|SYNC_TASK_SHADER_EXT_ACCELERATION_STRUCTURE_READ|SYNC_TASK_SHADER_EXT_DESCRIPTOR_BUFFER_READ_EXT|SYNC_TASK_SHADER_EXT_SHADER_BINDING_TABLE_READ|SYNC_TASK_SHADER_EXT_SHADER_SAMPLED_READ|SYNC_TASK_SHADER_EXT_SHADER_STORAGE_READ|SYNC_TASK_SHADER_EXT_SHADER_STORAGE_WRITE|SYNC_TASK_SHADER_EXT_UNIFORM_READ|SYNC_MESH_SHADER_EXT_ACCELERATION_STRUCTURE_READ|SYNC_MESH_SHADER_EXT_DESCRIPTOR_BUFFER_READ_EXT|SYNC_MESH_SHADER_EXT_SHADER_BINDING_TABLE_READ|SYNC_MESH_SHADER_EXT_SHADER_SAMPLED_READ|SYNC_MESH_SHADER_EXT_SHADER_STORAGE_READ|SYNC_MESH_SHADER_EXT_SHADER_STORAGE_WRITE|SYNC_MESH_SHADER_EXT_UNIFORM_READ|SYNC_RAY_TRACING_SHADER_ACCELERATION_STRUCTURE_READ|SYNC_RAY_TRACING_SHADER_DESCRIPTOR_BUFFER_READ_EXT|SYNC_RAY_TRACING_SHADER_SHADER_BINDING_TABLE_READ|SYNC_RAY_TRACING_SHADER_SHADER_SAMPLED_READ|SYNC_RAY_TRACING_SHADER_SHADER_STORAGE_READ|SYNC_RAY_TRACING_SHADER_SHADER_STORAGE_WRITE|SYNC_RAY_TRACING_SHADER_UNIFORM_READ|SYNC_FRAGMENT_SHADING_RATE_ATTACHMENT_FRAGMENT_SHADING_RATE_ATTACHMENT_READ|SYNC_FRAGMENT_DENSITY_PROCESS_EXT_FRAGMENT_DENSITY_MAP_READ_EXT|SYNC_TRANSFORM_FEEDBACK_EXT_TRANSFORM_FEEDBACK_COUNTER_READ_EXT|SYNC_TRANSFORM_FEEDBACK_EXT_TRANSFORM_FEEDBACK_COUNTER_WRITE_EXT|SYNC_TRANSFORM_FEEDBACK_EXT_TRANSFORM_FEEDBACK_WRITE_EXT|SYNC_ACCELERATION_STRUCTURE_BUILD_ACCELERATION_STRUCTURE_READ|SYNC_ACCELERATION_STRUCTURE_BUILD_ACCELERATION_STRUCTURE_WRITE|SYNC_ACCELERATION_STRUCTURE_BUILD_INDIRECT_COMMAND_READ|SYNC_ACCELERATION_STRUCTURE_BUILD_MICROMAP_READ_EXT|SYNC_ACCELERATION_STRUCTURE_BUILD_SHADER_STORAGE_READ|SYNC_ACCELERATION_STRUCTURE_BUILD_TRANSFER_READ|SYNC_ACCELERATION_STRUCTURE_BUILD_TRANSFER_WRITE|SYNC_ACCELERATION_STRUCTURE_COPY_ACCELERATION_STRUCTURE_READ|SYNC_ACCELERATION_STRUCTURE_COPY_ACCELERATION_STRUCTURE_WRITE|SYNC_ACCELERATION_STRUCTURE_COPY_TRANSFER_READ|SYNC_ACCELERATION_STRUCTURE_COPY_TRANSFER_WRITE|SYNC_MICROMAP_BUILD_EXT_MICROMAP_READ_EXT|SYNC_MICROMAP_BUILD_EXT_MICROMAP_WRITE_EXT|SYNC_MICROMAP_BUILD_EXT_TRANSFER_READ|SYNC_MICROMAP_BUILD_EXT_TRANSFER_WRITE|SYNC_COPY_TRANSFER_READ|SYNC_COPY_TRANSFER_WRITE|SYNC_RESOLVE_TRANSFER_READ|SYNC_RESOLVE_TRANSFER_WRITE|SYNC_BLIT_TRANSFER_READ|SYNC_BLIT_TRANSFER_WRITE|SYNC_CLEAR_TRANSFER_WRITE|SYNC_INDEX_INPUT_INDEX_READ|SYNC_VERTEX_ATTRIBUTE_INPUT_VERTEX_ATTRIBUTE_READ|SYNC_SUBPASS_SHADER_HUAWEI_ACCELERATION_STRUCTURE_READ|SYNC_SUBPASS_SHADER_HUAWEI_DESCRIPTOR_BUFFER_READ_EXT|SYNC_SUBPASS_SHADER_HUAWEI_INPUT_ATTACHMENT_READ|SYNC_SUBPASS_SHADER_HUAWEI_SHADER_BINDING_TABLE_READ|SYNC_SUBPASS_SHADER_HUAWEI_SHADER_SAMPLED_READ|SYNC_SUBPASS_SHADER_HUAWEI_SHADER_STORAGE_READ|SYNC_SUBPASS_SHADER_HUAWEI_SHADER_STORAGE_WRITE|SYNC_SUBPASS_SHADER_HUAWEI_UNIFORM_READ|SYNC_INVOCATION_MASK_HUAWEI_INVOCATION_MASK_READ_HUAWEI|SYNC_CLUSTER_CULLING_SHADER_HUAWEI_ACCELERATION_STRUCTURE_READ|SYNC_CLUSTER_CULLING_SHADER_HUAWEI_DESCRIPTOR_BUFFER_READ_EXT|SYNC_CLUSTER_CULLING_SHADER_HUAWEI_SHADER_BINDING_TABLE_READ|SYNC_CLUSTER_CULLING_SHADER_HUAWEI_SHADER_SAMPLED_READ|SYNC_CLUSTER_CULLING_SHADER_HUAWEI_SHADER_STORAGE_READ|SYNC_CLUSTER_CULLING_SHADER_HUAWEI_SHADER_STORAGE_WRITE|SYNC_CLUSTER_CULLING_SHADER_HUAWEI_UNIFORM_READ, ).
    Objects: 1
        [0] 0x562dfce21d10, type: 4, name: NULL

Average frame rate = 125.275

Process terminated
~~~ sh

**Comment by robertosfield** [comment] 2023-11-20 15:04
> Try enabling the synchronization layer, although it may be hard to pick out the shadow problems.

I had already started using synchronzation layer visa the VSG then via vkconfig, results posted in a reply below before I say this post from you.

> There is only one copy of each shadow cascade image, right?

Yes.  The buffering only applies to the light data being packed up and transferred each frame, the textures in GPU memory only have one copy.
 
> In ViewDependentState.cpp, you could try inserting another barrier in front of the shadow passes with src = VK_ACCESS_SHADER_READ_BIT, dest=VK_ACCESS_DEPTH_ATTACHMENT_WRITE_BIT

Thanks for the suggestion, will try it out once I've got back from walking my dog :-)

**Comment by robertosfield** [comment] 2023-11-20 17:55
I looked at the setup of RenderPass and associated vkImage/vkImageView in ViewDependentMap.cpp and all the settings looks consistent to Sasha Willems' cascaded shadow map example, and in that example I can't see any other synchronization primitives beyond the RenderPass setup.  It could be both the present VSG shadow map code and the Sasha Willems' code is wrong and missing an extra synchronization primitive that only NVidia drivers require.

The type of syncronization primitive we need requires us to syncronize the beginning of writing to the shadow map in the current frame with the reading from the shadow map in the previous frame.  This means we need to synchronize between submissions something we can't do with standard Vulkan pipeline barriers.

This leaves us with using a vkEvent or vkSemaphore, the later would be a higher/more general purpose one, but adding it will prevent the most of GPU parallelism between frames.  Writing to the resources that a previous frame might still be reading from is far more general topic than just shadow mapping.

**Comment by timoore** [comment] 2023-11-20 18:18
> I looked at the setup of RenderPass and associated vkImage/vkImageView in ViewDependentMap.cpp and all the settings looks consistent to Sasha Willems' cascaded shadow map example, and in that example I can't see any other synchronization primitives beyond the RenderPass setup. It could be both the present VSG shadow map code and the Sasha Willems' code is wrong and missing an extra synchronization primitive that only NVidia drivers require.

I see that you have the same subpass dependencies, and I would have thought they would be sufficient.

> The type of syncronization primitive we need requires us to syncronize the beginning of writing to the shadow map in the current frame with the reading from the shadow map in the previous frame. This means we need to synchronize between submissions something we can't do with standard Vulkan pipeline barriers.

I don't think that's correct. There's not really a notion of a frame in Vulkan, other than the synchronization introduced by presentation. On the other hand, barriers work for all memory accesses in a single queue; in fact, semaphores are only needed to synchronize between queues.

Did you try adding the barrier I suggested? 

Another case where there's only one copy of an image is the depth buffer, and you might think that it would suffer the same fate... but the subpass dependencies, which are equivalent to barriers, in RenderPass.cpp protect it.

> 
> This leaves us with using a vkEvent or vkSemaphore, the later would be a higher/more general purpose one, but adding it will prevent the most of GPU parallelism between frames. Writing to the resources that a previous frame might still be reading from is far more general topic than just shadow mapping.

Yes.

**Comment by robertosfield** [comment] 2023-11-20 18:28
I haven't tried inserting a pipeline barrier as it didn't seem appropriate for the problem being tackled. 

I can only guess that the synchronization associated with the shadow map RenderPass isn't being held back by the previous frames main 3D window RenderPass that is consuming the shadow maps.  I presume this issue is because there isn't anything the main window RenderPass that is putting a barrier on reading that could signal it's safe for the shadow map RenderPass is safe to begin.

**Comment by robertosfield** [comment] 2023-11-20 18:51
> Sorry I don't have a moment yet to test this myself, but it's possible that the stage masks in the shadow subpass dependencies should be `VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT | VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT`

You'll need to be more specific about what lines of code you are suggesting need changing as there are multiple lines of code that reference VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT and VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT.

**Comment by robertosfield** [comment] 2023-11-20 19:22
I have tried a few combinations of settings and haven't seen any change.

I have just done another look through Sacha Willems' shadowmappingcascade.cpp example and spotted that he sets up one depth pass vkRenderPass that is used by all the depth pass vkFramebuffer objects, while ViewDependentState.cpp sets up a vsg::RenderPass per depth pass vsg::Framebuffer.  I don't see how this would affect behavior, but might be worth refactoring ViewDependentState.cpp so it shares a RenderPass as I don't think there isn't any need to keep a RenderPass per depth pass vsg::Framebuffer.

I will do this refactor tomorrow and see if anything different happens.

**Comment by rolandhill** [comment] 2023-11-20 21:33
That's great that you can replicate the problem. I'm following along the
discussion between you and Tim, but I'm afraid it's above my skill level.
All I can do is offer to test any potential solution.

Thanks & regards,
Roland

**Comment by timoore** [comment] 2023-11-21 08:03
I stayed up far too late, trying various combinations of additional subpass dependency flags to no avail... now I'm wondering if the problem is a data race in the lights or viewport data uniform buffers? I do see other artifacts on nvidia that I don't see with AMD iGPU; see #980.

**Comment by timoore** [comment] 2023-11-21 08:22
A data point: the problem disappears if one disables the use of a separate transfer queue.

**Comment by robertosfield** [comment] 2023-11-21 08:35
Curious. THe TransferTask is triple buffered while the shadow depth map is single- buffered so I would expect it to be the most likely cause of a race.  Will investigate.

**Comment by timoore** [comment] 2023-11-21 08:43
> Curious. THe TransferTask is triple buffered while the shadow depth map is single- buffered so I would expect it to be the most likely cause of a race. Will investigate.

As discussed in #980, the transfer task staging buffers are triple-buffered, but the destination buffers are single buffered, and the transfer task doesn't wait for any semaphore that might signal that it is safe to proceed.

**Comment by robertosfield** [comment] 2023-11-21 10:54
I am in process of adding a wait semaphore to the transfer queue submission done in TransferTask::transferDynamicData().  I have created a [TransferTaskSynchronizationFix](https://github.com/vsg-dev/VulkanSceneGraph/tree/TransferTaskSynchronizationFix) branch for this work as this isn't a shadow mapping issue, it's just shadow mapping illustrates it's nicely.

I am reasonably confident that I can pass the previous frames frame complete semaphore used to signal presentation as the wait semaphore for the transfer task, and really should have done this in the original TransferTask implementation.  I expect to have solution checked in the next hour or two.

**Comment by kannode** [comment] 2023-11-21 11:45
Are there two sources of the same shadow data?

Relevant Theory

**Comment by timoore** [comment] 2023-11-21 12:00
> I am reasonably confident that I can pass the previous frames frame complete semaphore used to signal presentation as the wait semaphore for the transfer task, and really should have done this in the original TransferTask implementation. I expect to have solution checked in the next hour or two.

I hope you're getting along with this. As I understand it, you can't wait on the same semaphore more than once before it is signalled... one of the advantages of timeline semaphores.

**Comment by robertosfield** [comment] 2023-11-21 15:17
> Are there two sources of the same shadow data? Relevant Theory

The only part that generates the shadow map and light data is vsg::ViewDependentState.

The issue looks to be the separate vsg::Queue used for transferring the light data that is used on NVidia graphics cards/drivers but that transfer queue hasn't been waiting for the previous frame to complete.

**Comment by robertosfield** [comment] 2023-11-21 15:30
> > I am reasonably confident that I can pass the previous frames frame complete semaphore used to signal presentation as the wait semaphore for the transfer task, and really should have done this in the original TransferTask implementation. I expect to have solution checked in the next hour or two.
> 
> I hope you're getting along with this. As I understand it, you can't wait on the same semaphore more than once before it is signalled... one of the advantages of timeline semaphores.

I haven't yet got it to work yet, thought most of the code required is now in place.  I have been tackling other tasks as well so just now jumping back to figuring out how to wire things up robustly.

**Comment by robertosfield** [comment] 2023-11-21 17:38
I now have vsgshadow running without Jitters on Kubuntu 22.04 system with Geforce 2060 and NVidia drivers :-)

Adding a wait vk/vsg::Semaphore to the vsg::TransferTask was required, with the previous frame completion signally this wait vk/vsg::Semaphore.  Currently my Viewer code is wiring this up to happen on every frame for both the early and late TransferTask which isn't appropriate as the TransferTask only submit work when they have something to do, so there is no need for signally a Semaphore that's never waited upon.  

This untidiness is now resulting in Vulkan debug layer warning:

~~~ sh
UNASSIGNED-CoreValidation-DrawState-QueueForwardProgress(ERROR / SPEC): msgNum: -400166253 - Validation Error: [ UNASSIGNED-CoreValidation-DrawState-QueueForwardProgress ] Object 0: handle = 0xf56c9b0000000004, type = VK_OBJECT_TYPE_SEMAPHORE; Object 1: handle = 0x5653fa03b870, type = VK_OBJECT_TYPE_QUEUE; Object 2: handle = 0x5653fa03b870, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xe825f293 | vkQueueSubmit(): pSubmits[0].pSignalSemaphores[1] is signaling VkQueue 0x5653fa03b870[] (VkSemaphore 0xf56c9b0000000004[]) that was previously signaled by VkQueue 0x5653fa03b870[] but has not since been waited on by any queue.
~~~

So ti's a case of two steps forward and one step back.  My code is experimentally at this point, learning what is possible and what the pitfalls might be.  I had hoped to be able to just use standard Vulkan 1.1 vkSemaphore as the VSG compiles against 1.1.

I will ponder the issue further.  I had hoped to wrap up a proper fix today, but alas this one needs a bit more work.

**Comment by robertosfield** [comment] 2023-11-22 12:04
I now have a combination of semaphores in TransferTask and RecordAndSubmitTask that are working reliably - no oddities in the shadows and no Vulkan debug errors.  Perhaps looks good too.

This work has shone a light on some aspects of TransferTask that were incomplete and other parts that were built in prep for functionality that was never/will never be required so there has been opportunities to simply it in places.  This clean up has helped the process of fixing the issues, but also just adds an extra layer of stuff I need to double check before checking in.

**Comment by robertosfield** [comment] 2023-11-22 13:00
I have completed my work on refactoring TransferTask/RecordAndSubmitTask and have created a PR that I'll merged with VSG master once all the automated builds have been reported as successful:

https://github.com/vsg-dev/VulkanSceneGraph/pull/1033

**Comment by robertosfield** [comment] 2023-11-22 13:37
Fix now merged with VSG master.

**Closed by robertosfield** 2023-11-22 13:37 UTC
