### ISSUE TITLE
Can not select from all availiable devices

### ISSUE THREAD

**Issue by spezialspezial** [vsg-dev/VulkanSceneGraph#409] opened 2022-02-25 09:55 UTC
**Describe the bug**

Hi, 

with the currently hardcoded apiVersion = VK_API_VERSION_1_0 in vsg::Instance I can not get all devices/drivers availiable on my system. In my case, especially the AMD pro driver is not selectable.

Using ->

```

//https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkEnumerateInstanceVersion.html
uint32_t inst_api_version;
PFN_vkEnumerateInstanceVersion vkEnumerateInstanceVersion = reinterpret_cast<PFN_vkEnumerateInstanceVersion>(vkGetInstanceProcAddr(nullptr, "vkEnumerateInstanceVersion"));
if(vkEnumerateInstanceVersion) {
	vkEnumerateInstanceVersion(&inst_api_version);
	std::cout << "have vkEnumerateInstanceVersion: " << apiVersionString(inst_api_version) << std::endl;
} else {
	inst_api_version = VK_API_VERSION_1_0;
}

```

I can get instance api version 1.3.204 and thus 2 more devices in my case, including the pro driver.

Api Version: 1.1.182
Driver Version: 0.0.0.1
Vendor ID: Mesa
Device ID: 0
Device Type: CPU
Device Name: llvmpipe (LLVM 12.0.0, 256 bits)
pipelineCacheUUID: 58 35 6c

Api Version: 1.2.182
Driver Version: 21.0.128.6
Vendor ID: AMD
Device ID: 22191
Device Type: DISCRETE GPU
Device Name: AMD RADV POLARIS10
pipelineCacheUUID: 42 e4 11

Api Version: 1.2.197
Driver Version: 2.0.3.15
Vendor ID: AMD
Device ID: 22191
Device Type: DISCRETE GPU
Device Name: Radeon RX 580 Series
pipelineCacheUUID: 18 23 2d

Maybe worth looking into for these special requirements cases?

**Desktop:**
Ubuntu 20.04.3 LTS, AMD RX 580, amdgpu 21.50.50000-1
VulkanSceneGraph c220f4caba410c8d97eb8a98173b47cebe6b5b85

**Comment by robertosfield** [comment] 2022-02-25 10:39
Hi,

The vulkan version currently defaults to VK_API_VERSION_1_0, it's not
hardwired.  You can select other versions.  WindpwTraits has a
vulkanVersion field that one uses to bump up the version required.  The
vsgraytracing, vsgheadless and vgscreenshot examples also have code paths
that set the required version.  The vsg::Instance constructor also takes
the vulkanVersion as parameter:

     Instance(const Names& instanceExtensions, const Names& layers,
uint32_t vulkanApiVersion = VK_API_VERSION_1_0, AllocationCallbacks*
allocator = nullptr);

With querying available devices I would have expected drivers to be
backwards compatible with VK_API_VERSION_1_0, even if they are capable of
supporting later versions of the API,  Something odd is going on with your
system's AMD drivers.

What happens when you run:

    vsgdeviceselection --list

**Comment by spezialspezial** [comment] 2022-02-25 11:02
> it's not hardwired

Ah, ok, I will check it out. Thanks for getting back.

> With querying available devices I would have expected drivers to be backwards compatible with VK_API_VERSION_1_0, even if they are capable of supporting later versions of the API

Yes, me too, very unintuitive. 

> Something odd is going on with your system's AMD drivers.

I'm not excluding that possibility.

**Comment by spezialspezial** [comment] 2022-02-25 11:08
> What happens when you run: vsgdeviceselection --list

It gives me only one device, the opensource driver (same codebase as the ubuntu kernel driver):
physicalDevices.size() = 1
    matched ref_ptr<vsg::PhysicalDevice>(vsg::PhysicalDevice 0x557db78464f0) Radeon RX 580 Series deviceType = 2

**Comment by robertosfield** [comment] 2022-02-25 11:46
I've reopened as I'd like to get to the bottom of what is going on.  Could you try modifying vsgdeviceselection to that is sets difference vulkanVersions i.e. by adding:

    windowTraits->vulkanVersion = VK_API_VERSION_1_2; // or VK_API_VERSION_1_1

Prior to the Window::create() call.

Then have a look at the output from --list.

**Comment by spezialspezial** [comment] 2022-02-25 12:16
Weird, seems like can only get one device:

physicalDevices.size() = 1
    matched ref_ptr<vsg::PhysicalDevice>(vsg::PhysicalDevice 0x5555567b6a00) Radeon RX 580 Series deviceType = 2

**Comment by spezialspezial** [comment] 2022-02-25 12:19
using the dynamic PFN_vkEnumerateInstanceVersion wich returns  1.3.204.0 I get 3 of them

physicalDevices.size() = 3
    matched ref_ptr<vsg::PhysicalDevice>(vsg::PhysicalDevice 0x5640dde20a70) llvmpipe (LLVM 12.0.0, 256 bits) deviceType = 4
    matched ref_ptr<vsg::PhysicalDevice>(vsg::PhysicalDevice 0x5640dde20ee0) AMD RADV POLARIS10 deviceType = 2
    matched ref_ptr<vsg::PhysicalDevice>(vsg::PhysicalDevice 0x5640dde21350) Radeon RX 580 Series deviceType = 2

**Comment by spezialspezial** [comment] 2022-02-25 12:20
Ah, VK_API_VERSION_1_3 gives me 3 again

**Comment by spezialspezial** [comment] 2022-02-25 12:28
maybe a "latest" option using vkEnumerateInstanceVersion would be good feature

**Comment by robertosfield** [comment] 2022-02-25 12:30
Well dang, that's one odd result.  It's great that that it's giving a wider range of device options, but seem pretty odd that these drivers aren't backwards compatible.  Pretty sure this would prevent lots of Vulkan apps from using these.  Might be worth seeing if there is any official guidance from AMD on this.

To help with experiments I've just done the adding the following to the new_delete branch of vsgExamples: [vsgdeviceselection mods](https://github.com/vsg-dev/vsgExamples/commit/6ac9c0d5eb7f677feccc63253981fef3bf745902).  I'm right in the middle testing the new vsg::Allocator (in the new_delete branches osg VSG/vsgExamples) functionality so can't go add other stuff to the core, I'll roll some of this code with VSG/vsgExample master once the new_delete branhces are merged with master.

**Comment by spezialspezial** [comment] 2022-02-25 12:32
Cool. I might upgrade to RTX this afternoon, if there are AMD behaviors you want me to try now is the time. I could put it in an old box later tho.

**Comment by robertosfield** [comment] 2022-02-25 12:36
It does sound  like we'll need to implement use of vkEnumerateInstanceVersion in some fashion.  So far I haven't seen any issues with NVIdia and Intel drivers in this way.   I'll pop into my TODO list.

**Comment by spezialspezial** [comment] 2022-02-25 12:39
If you go for a AMD testing card maybe check AMD pro drivers are availiable for the specific type to get the full experience.

**Comment by robertosfield** [comment] 2022-02-25 12:47
Looking at [https://www.amd.com/en/support] the AMD5700G I'm thinking of getting looks to be supported under Window PRO drivers, so... hopefully it'll also be supported under Linux.

**Comment by robertosfield** [comment] 2022-03-09 18:25
A quick update on this topic as I've begun looking into.  First step has been to test out vkEnumerateInstanceVersion so I've added it's use to [vsgdeviceselection](https://github.com/vsg-dev/vsgExamples/commit/c3529f609a9ebd1eca34885b7314a986e93a63f9).

The next step is to install my new AMD Ryzen 7 5700G processor that's sitting on my desk ready to oust the AMD 2700 that's been my work horse 3 years.  I'll installed that tomorrow and work to get it's integrated graphics working.  Aim will be to get the VSG to work out of the box on AMD systems rather require specific settings.

**Comment by robertosfield** [comment] 2022-03-13 17:12
@spezialspezial I now have my AMD Ryzen 7 5700G processor installed in my dev system, replacing AMD 2700 and also optionally replacing the Geforce2060 as well thanks to the GPU on the processor.  Power consumption at idle is 20W lower so a good result there.

I'm using the open source RADV drivers.  The Pro drivers just talk about Ubuntu 20.04 for support, and I have Kubuntu 21.10 on this system so am wary of how well it'd work.  Thoughts?

The RADV drivers have worked out of the box, and are automatically selected when I run VSG apps.  A recent community patch fixed Xcb resize problems with AMD+Intel graphics so everything has worked well for me.  

The only oddity is that my max framerate with Geforce2060 installed on a large synthetic city model has dropped by 80%, even though the CPU is faster in all other respects.  I looks like the IPC when dispatching data to vulkan is hit harder on the AMD5700G vs AMD2700 as perf is reporting a much lower IPC when running the same model/camera paths/window resolution.  It's an oddity as generally this CPU has really good IPC values.  I am wondering if the vulkan drivers don't support the AMD5700G processor properly causing a regression in certain usage cases.

**Comment by robertosfield** [comment] 2022-05-16 10:25
I have just checked (827023e500337c8e4876c48e035673218373b582) in to VSG master in the addition of:

            // query the vulkan instance version available
            vkEnumerateInstanceVersion(&vulkanVersion);

To the WindowTraits::defaults() function that is called by the WindowTaits constructor.  I don't have the AMD Pro drivers on my system so can't test it this resolves the issues.  @spezialspezial could update to VSG master and see if this helps on your system with the AMD Pro drivers?

**Closed** 2022-05-21 08:33 UTC
