### ISSUE TITLE
DescriptorPool recyled the descriptorset,but dependency DescriptorSetLayout was destroyed.

### ISSUE THREAD

**Issue by simwangrui** [vsg-dev/VulkanSceneGraph#465] opened 2022-06-25 04:16 UTC
Hi,
I try to Implement dynamic creation and destruction of my RTT RenerGraph,when  running the code with --debug param,vulkan reported an error:

VUID-VkWriteDescriptorSet-dstSet-00320(ERROR / SPEC): msgNum: 148949623 - Validation Error: [ VUID-VkWriteDescriptorSet-dstSet-00320 ] Object 0: handle = 0x7cd292000000004f, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0x8e0ca77 | vkUpdateDescriptorSets() pDescriptorWrites[0] failed write update validation for VkDescriptorSet 0x7cd292000000004f[] with error: Cannot call vkUpdateDescriptorSets() to perform write update on VkDescriptorSet 0x7cd292000000004f[] allocated with VkDescriptorSetLayout 0x40b43c0000000049[] which has been destroyed. The Vulkan spec states: dstSet must be a valid VkDescriptorSet handle (https://vulkan.lunarg.com/doc/view/1.3.211.0/windows/1.3-extensions/vkspec.html#VUID-VkWriteDescriptorSet-dstSet-00320)
    Objects: 1
        [0] 0x7cd292000000004f, type: 23, name: NULL

I track the code,the descriptorset  was recyled by DescriptorPool, but DescriptorSetLayout which using to create descriptorset itself was destroyed.

 - OS: window10
 - VSG Version: the lastest

this is my code:

#include <vsg/all.h>
#include <vsgXchange/all.h>

#include <algorithm>
#include <chrono>
#include <iostream>
#include <thread>

vsg::ref_ptr<vsg::RenderGraph> createOffscreenRendergraph(vsg::ref_ptr<vsg::Device> device, const VkExtent2D& extent,
	vsg::ImageInfo& colorImageInfo, vsg::ImageInfo& depthImageInfo)
{
	VkExtent3D attachmentExtent{ extent.width, extent.height, 1 };
	
	auto colorImage = vsg::Image::create();
	colorImage->imageType = VK_IMAGE_TYPE_2D;
	colorImage->format = VK_FORMAT_R8G8B8A8_UNORM;
	colorImage->extent = attachmentExtent;
	colorImage->mipLevels = 1;
	colorImage->arrayLayers = 1;
	colorImage->samples = VK_SAMPLE_COUNT_1_BIT;
	colorImage->tiling = VK_IMAGE_TILING_OPTIMAL;
	colorImage->usage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
	colorImage->initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
	colorImage->flags = 0;
	colorImage->sharingMode = VK_SHARING_MODE_EXCLUSIVE;
	auto colorImageView = createImageView(device, colorImage, VK_IMAGE_ASPECT_COLOR_BIT);

	auto colorSampler = vsg::Sampler::create();
	colorSampler->flags = 0;
	colorSampler->magFilter = VK_FILTER_LINEAR;
	colorSampler->minFilter = VK_FILTER_LINEAR;
	colorSampler->mipmapMode = VK_SAMPLER_MIPMAP_MODE_LINEAR;
	colorSampler->addressModeU = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
	colorSampler->addressModeV = colorSampler->addressModeU;
	colorSampler->addressModeW = colorSampler->addressModeU;
	colorSampler->mipLodBias = 0.0f;
	colorSampler->maxAnisotropy = 1.0f;
	colorSampler->minLod = 0.0f;
	colorSampler->maxLod = 1.0f;
	colorSampler->borderColor = VK_BORDER_COLOR_FLOAT_OPAQUE_WHITE;

	colorImageInfo.imageView = colorImageView;
	colorImageInfo.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
	colorImageInfo.sampler = colorSampler;

	VkFormat depthFormat = VK_FORMAT_D24_UNORM_S8_UINT;
	auto depthImage = vsg::Image::create();
	depthImage->imageType = VK_IMAGE_TYPE_2D;
	depthImage->extent = attachmentExtent;
	depthImage->mipLevels = 1;
	depthImage->arrayLayers = 1;
	depthImage->samples = VK_SAMPLE_COUNT_1_BIT;
	depthImage->format = depthFormat;
	depthImage->tiling = VK_IMAGE_TILING_OPTIMAL;
	depthImage->usage = VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT;
	depthImage->initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
	depthImage->flags = 0;
	depthImage->sharingMode = VK_SHARING_MODE_EXCLUSIVE;

	depthImageInfo.sampler = nullptr;
	depthImageInfo.imageView = vsg::createImageView(device, depthImage, VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT);
	depthImageInfo.imageLayout = VK_IMAGE_LAYOUT_GENERAL;

	vsg::RenderPass::Attachments attachments(2);
	attachments[0].format = VK_FORMAT_R8G8B8A8_UNORM;
	attachments[0].samples = VK_SAMPLE_COUNT_1_BIT;
	attachments[0].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
	attachments[0].storeOp = VK_ATTACHMENT_STORE_OP_STORE;
	attachments[0].stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
	attachments[0].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
	attachments[0].initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
	attachments[0].finalLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;

	attachments[1].format = depthFormat;
	attachments[1].samples = VK_SAMPLE_COUNT_1_BIT;
	attachments[1].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
	attachments[1].storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
	attachments[1].stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
	attachments[1].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
	attachments[1].initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
	attachments[1].finalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;

	vsg::AttachmentReference colorReference = { 0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL };
	vsg::AttachmentReference depthReference = { 1, VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL };
	vsg::RenderPass::Subpasses subpassDescription(1);
	subpassDescription[0].pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
	subpassDescription[0].colorAttachments.emplace_back(colorReference);
	subpassDescription[0].depthStencilAttachments.emplace_back(depthReference);

	vsg::RenderPass::Dependencies dependencies(2);

	dependencies[0].srcSubpass = VK_SUBPASS_EXTERNAL;
	dependencies[0].dstSubpass = 0;
	dependencies[0].srcStageMask = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
	dependencies[0].dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
	dependencies[0].srcAccessMask = VK_ACCESS_SHADER_READ_BIT;
	dependencies[0].dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
	dependencies[0].dependencyFlags = VK_DEPENDENCY_BY_REGION_BIT;

	dependencies[1].srcSubpass = 0;
	dependencies[1].dstSubpass = VK_SUBPASS_EXTERNAL;
	dependencies[1].srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
	dependencies[1].dstStageMask = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
	dependencies[1].srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
	dependencies[1].dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
	dependencies[1].dependencyFlags = VK_DEPENDENCY_BY_REGION_BIT;

	auto renderPass = vsg::RenderPass::create(device, attachments, subpassDescription, dependencies);

	auto fbuf = vsg::Framebuffer::create(renderPass, vsg::ImageViews{ colorImageInfo.imageView, depthImageInfo.imageView }, extent.width, extent.height, 1);

	auto rendergraph = vsg::RenderGraph::create();
	rendergraph->renderArea.offset = VkOffset2D{ 0, 0 };
	rendergraph->renderArea.extent = extent;
	rendergraph->framebuffer = fbuf;

	rendergraph->clearValues.resize(2);
	rendergraph->clearValues[0].color = { {0.4f, 0.2f, 0.4f, 1.0f} };
	rendergraph->clearValues[1].depthStencil = VkClearDepthStencilValue{ 0.0f, 0 };

	return rendergraph;
}

struct Merge : public vsg::Inherit<vsg::Operation, Merge>
{
    Merge(const vsg::Path& in_path, vsg::observer_ptr<vsg::Viewer> in_viewer, vsg::ref_ptr<vsg::Group> in_attachmentPoint, vsg::ref_ptr<vsg::Node> in_node, const vsg::CompileResult& in_compileResult):
        path(in_path),
        viewer(in_viewer),
        attachmentPoint(in_attachmentPoint),
        node(in_node),
        compileResult(in_compileResult) {}

    vsg::Path path;
    vsg::observer_ptr<vsg::Viewer> viewer;
    vsg::ref_ptr<vsg::Group> attachmentPoint;
    vsg::ref_ptr<vsg::Node> node;
    vsg::CompileResult compileResult;

    void run() override
    {
        std::cout<<"Merge::run() path = "<<path<<", "<<attachmentPoint<<", "<<node<<std::endl;

        vsg::ref_ptr<vsg::Viewer> ref_viewer = viewer;
        if (ref_viewer)
        {
            updateViewer(*ref_viewer, compileResult);
        }

        attachmentPoint->addChild(node);
    }
};

struct LoadViewOperation : public vsg::Inherit<vsg::Operation, LoadViewOperation>
{
    LoadViewOperation(vsg::ref_ptr<vsg::Viewer> in_viewer, vsg::ref_ptr<vsg::Device> in_device, int32_t in_x, int32_t in_y, uint32_t in_width, uint32_t in_height, vsg::ref_ptr<vsg::Group> in_attachmentPoint, const vsg::Path& in_filename, vsg::ref_ptr<vsg::Options> in_options) :
        viewer(in_viewer),
		device(in_device),
        x(in_x),
        y(in_y),
        width(in_width),
        height(in_height),
        attachmentPoint(in_attachmentPoint),
        filename(in_filename),
        options(in_options)
    {
    }

	vsg::ref_ptr<vsg::Device>      device;
    vsg::observer_ptr<vsg::Viewer> viewer;
    int32_t x, y;
    uint32_t width, height;
    vsg::ref_ptr<vsg::Group> attachmentPoint;
    vsg::Path filename;
    vsg::ref_ptr<vsg::Options> options;

    void run() override
    {
        vsg::ref_ptr<vsg::Viewer> ref_viewer = viewer;

        if (auto node = vsg::read_cast<vsg::Node>(filename, options))
        {
            vsg::ComputeBounds computeBounds;
            node->accept(computeBounds);

            vsg::dvec3 centre = (computeBounds.bounds.min + computeBounds.bounds.max) * 0.5;
            double radius = vsg::length(computeBounds.bounds.max - computeBounds.bounds.min) * 0.5;
            double nearFarRatio = 0.001;

            // set up the camera
            auto lookAt = vsg::LookAt::create(centre + vsg::dvec3(0.0, -radius * 3.5, 0.0),
                                            centre, vsg::dvec3(0.0, 0.0, 1.0));

            auto perspective = vsg::Perspective::create(30.0, static_cast<double>(width) / static_cast<double>(height),
                                                        nearFarRatio * radius, radius * 4.5);

            auto viewportState = vsg::ViewportState::create(x, y, width, height);

            auto camera = vsg::Camera::create(perspective, lookAt, viewportState);
            auto view = vsg::View::create(camera, node);

			
			VkExtent2D extent{ 1920, 1080 };
			auto colorImage = vsg::ImageInfo::create();
			auto depthImage = vsg::ImageInfo::create();

            auto renderGraph = createOffscreenRendergraph(device, extent, *colorImage,* depthImage);
            renderGraph->setClearValues({{0.2f, 0.2f, 0.2f, 1.0f}});
			renderGraph->addChild(view);

			auto frame_buffer = renderGraph->framebuffer;
            ref_viewer->compileManager->add(*frame_buffer, view);

			auto result = ref_viewer->compileManager->compile(renderGraph);

            if (result) ref_viewer->addUpdateOperation(Merge::create(filename, viewer, attachmentPoint, renderGraph, result));
        }
    }
};

int main(int argc, char** argv)
{

	vsg::CommandLine arguments(&argc, argv);

	auto options = vsg::Options::create();
	options->sharedObjects = vsg::SharedObjects::create();
	options->fileCache = vsg::getEnv("VSG_FILE_CACHE");
	options->paths = vsg::getEnvPaths("VSG_FILE_PATH");

	options->add(vsgXchange::all::create());

	arguments.read(options);

	

	uint32_t vulkanVersion = VK_API_VERSION_1_0;

	auto debugLayer = arguments.read({ "--debug", "-d" });
	auto apiDumpLayer = arguments.read({ "--api", "-a" });

	// create instance
	vsg::Names instanceExtensions;
	vsg::Names requestedLayers;
	if (debugLayer || apiDumpLayer)
	{
		instanceExtensions.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
		instanceExtensions.push_back(VK_EXT_DEBUG_REPORT_EXTENSION_NAME);
		requestedLayers.push_back("VK_LAYER_KHRONOS_validation");
		requestedLayers.push_back("VK_LAYER_LUNARG_standard_validation");
		if (apiDumpLayer) requestedLayers.push_back("VK_LAYER_LUNARG_api_dump");
	}

	vsg::Names validatedNames = vsg::validateInstancelayerNames(requestedLayers);

	auto instance = vsg::Instance::create(instanceExtensions, validatedNames, vulkanVersion);
	auto[physicalDevice, queueFamily] = instance->getPhysicalDeviceAndQueueFamily(VK_QUEUE_GRAPHICS_BIT);
	if (!physicalDevice || queueFamily < 0)
	{
		std::cout << "Could not create PhysicalDevice" << std::endl;
		return 0;
	}

	vsg::Names deviceExtensions;
	vsg::QueueSettings queueSettings{ vsg::QueueSetting{queueFamily, {1.0}} };

	auto device = vsg::Device::create(physicalDevice, queueSettings, validatedNames, deviceExtensions);

	auto viewer = vsg::Viewer::create();

	auto commandGraph = vsg::CommandGraph::create(device, queueFamily);
	viewer->assignRecordAndSubmitTaskAndPresentation({ commandGraph });

	viewer->compile();

	auto loadThreads = vsg::OperationThreads::create(16, viewer->status);

	vsg::observer_ptr<vsg::Viewer> observer_viewer(viewer);

	loadThreads->add(LoadViewOperation::create(observer_viewer, device, 50, 50, 512, 480, commandGraph, "models/lz.vsgt", options));

	int numFrames = 0;

	while (viewer->advanceToNextFrame())
	{
		numFrames++;
		
		viewer->handleEvents();

		if (commandGraph->children.size() > 0)
		{
			vkDeviceWaitIdle(device->getDevice());
			auto itor = commandGraph->children.begin();
			commandGraph->children.erase(itor);

			loadThreads->add(LoadViewOperation::create(observer_viewer, device, 600, 50, 512, 480, commandGraph, "models/lz.vsgt", options));
		}
		

		viewer->update();

		viewer->recordAndSubmit();
	}

	return 0;
}

**Comment by robertosfield** [comment] 2022-06-25 11:03
Could you create an compilable example that I could run to reproduce the problem, as the copy and paste has mangled the example.  Thanks.

**Comment by simwangrui** [comment] 2022-06-25 13:01
Hi,
Does compressed package of example source files can be used？
[vsg_dynamic_rendergraph.zip](https://github.com/vsg-dev/VulkanSceneGraph/files/8984767/vsg_dynamic_rendergraph.zip)

**Comment by robertosfield** [comment] 2022-06-25 17:47
Thanks for the example, I've downloaded it and created a CMakeLists.txt for it based on MyFirstVsgApplication example.  If I run it I just get message output of the form:

Merge::run() path = models/lz.vsgt, ref_ptr<vsg::Group>(vsg::CommandGraph 0x55f0596b7870), ref_ptr<vsg::Node>(vsg::RenderGraph 0x55f0596bf938)
Merge::run() path = models/lz.vsgt, ref_ptr<vsg::Group>(vsg::CommandGraph 0x55f0596b7870), ref_ptr<vsg::Node>(vsg::RenderGraph 0x55f0596bf938)
Merge::run() path = models/lz.vsgt, ref_ptr<vsg::Group>(vsg::CommandGraph 0x55f0596b7870), ref_ptr<vsg::Node>(vsg::RenderGraph 0x55f0596bf938)
Merge::run() path = models/lz.vsgt, ref_ptr<vsg::Group>(vsg::CommandGraph 0x55f0596b7870), ref_ptr<vsg::Node>(vsg::RenderGraph 0x55f0596bf938)
M

Written to the console.  I don't get any Vulkan debug errors like you posted.  This is on my AMD5700G/Kubuntu21.10/Mesa driver system and VSG master from today.

**Comment by robertosfield** [comment] 2022-06-25 17:48
Umm... it looks like my driver no longer supports the old validation layer string values:

bin/dynamicviewscrash -d 
Warning: requested invalid layer : VK_LAYER_KHRONOS_validation
Warning: requested invalid layer : VK_LAYER_LUNARG_standard_validation

I will need to investigate.

**Comment by simwangrui** [comment] 2022-06-25 22:03
Hi,
Thinks for reply.My detailed running environment：
card: NVIDIA GeForce RTX 2080
driver:511.79
OS：Windows 10 desktop
vulkan  sdk:1.3.211.0

Two weeks ago, I encountered the same problem: after destroying the previous rendergraph, I created a new rendergraph, Vulkan reported the same error. The difference is that descriptorsetlayout and descriptorset are created by myself. If I use vsg:: ref_ ptr<DescriptorsetLayout> refers to external created descriptorsetlayout ,which life cycle is longer than descriptorset, And the descriptorset is created with this descriptorsetlayout. so it works well without any error messages.

**Comment by robertosfield** [comment] 2022-06-26 08:23
That's a really helpful clue, I've created a DescriptorSetFix branch and check in the addition a ref_ptr<DescriptorSetLayout> to the DescriptorSet::Implementation:

   cf7bd9187091b2e5fbb444f1144c3fcd73944a39

I need to think through the reuse mechanism to make sure the DescriptorSetLayout end up being coherent, but this commit might be enough to know that it's a partial solution.

**Comment by robertosfield** [comment] 2022-06-26 11:41
I have switched back to using VulkanSDK and have the debug layer working again, using your example I can confirm that I'm getting the error you reported:

Objects: 1
        [0] pointer, type: 3, name: NULL
VUID-VkWriteDescriptorSet-dstSet-00320(ERROR / SPEC): msgNum: 148949623 - Validation Error: [ VUID-VkWriteDescriptorSet-dstSet-00320 ] Object 0: handle = pointer, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = pointer | vkUpdateDescriptorSets() pDescriptorWrites[0] failed write update validation for VkDescriptorSet pointer[] with error: Cannot call vkUpdateDescriptorSets() to perform write update on VkDescriptorSet pointer[] allocated with VkDescriptorSetLayout pointer[] which has been destroyed. The Vulkan spec states: dstSet must be a valid VkDescriptorSet handle (https://vulkan.lunarg.com/doc/view/1.3.216.0/linux/1.3-extensions/vkspec.html#VUID-VkWriteDescriptorSet-dstSet-00320)

Once I apply cf7bd9187091b2e5fbb444f1144c3fcd73944a39 this error goes away.  I've done a wide review and feel that this solution is the best one, so I'll merge that with master.

This doesn't resolve all the problems with the test program though - I'm getting streams of these errors:

VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251(ERROR / SPEC): msgNum: -1094930823 - Validation Error: [ VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251 ] Object 0: handle = pointer, type = VK_OBJECT_TYPE_DEVICE; | MessageID = poin
ter | vkCreateImage(): Format VK_FORMAT_D24_UNORM_S8_UINT is not supported for this combination of parameters and VkGetPhysicalDeviceImageFormatProperties returned back VK_ERROR_FORMAT_NOT_SUPPORTED. The Vulkan spec states: Each of the follo
wing values (as described in Image Creation Limits) must not be undefined : imageCreateMaxMipLevels, imageCreateMaxArrayLayers, imageCreateMaxExtent, and imageCreateSampleCounts (https://vulkan.lunarg.com/doc/view/1.3.216.0/linux/1.3-extensi
ons/vkspec.html#VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251)
    Objects: 1
        [0] pointer, type: 3, name: NULL
VUID-VkImageViewCreateInfo-None-02273(ERROR / SPEC): msgNum: 1066700753 - Validation Error: [ VUID-VkImageViewCreateInfo-None-02273 ] Object 0: handle = pointer, type = VK_OBJECT_TYPE_IMAGE; | MessageID = pointer | vkCreateImageView(): pCrea
teInfo->format VK_FORMAT_D24_UNORM_S8_UINT with tiling VK_IMAGE_TILING_OPTIMAL has no supported format features on this physical device. The Vulkan spec states: The format features of the resultant image view must contain at least one bit (h
ttps://vulkan.lunarg.com/doc/view/1.3.216.0/linux/1.3-extensions/vkspec.html#VUID-VkImageViewCreateInfo-None-02273)
    Objects: 1
        [0] pointer, type: 10, name: NULL
VUID-VkSubpassDescription-pDepthStencilAttachment-02650(ERROR / SPEC): msgNum: -996339680 - Validation Error: [ VUID-VkSubpassDescription-pDepthStencilAttachment-02650 ] Object 0: handle = pointer, type = VK_OBJECT_TYPE_DEVICE; | MessageID =
 pointer | vkCreateRenderPass(): Depth Stencil pSubpasses[0].pDepthStencilAttachment format (VK_FORMAT_D24_UNORM_S8_UINT) does not contain VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT. The Vulkan spec states: If pDepthStencilAttachment is 
not NULL and the attachment is not VK_ATTACHMENT_UNUSED then it must have an image format whose potential format features contain VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT (https://vulkan.lunarg.com/doc/view/1.3.216.0/linux/1.3-extensio
ns/vkspec.html#VUID-VkSubpassDescription-pDepthStencilAttachment-02650)

Is this something you see as well?

**Comment by robertosfield** [comment] 2022-06-26 14:15
I was able to resolve the Vulkan debug error with the test program just by changing the depth format to one supported by my hardware/driver, so it was just a configuration issue rather than an underlying bug.  I'm  going to closing this PR now as I believe the fix I've checked in and merged with master resolve the bug in DescriptorSet reuse.

**Closed by robertosfield** 2022-06-26 14:15 UTC

**Comment by simwangrui** [comment] 2022-06-26 15:22
Hi,
I only merge DescriptorSet changes,so it still support VK_LAYER_LUNARG_standard_validation,and it now work perfect without any error.Thinks a lot.
Best wishes

**Comment by robertosfield** [comment] 2022-06-26 16:13
On Sun, 26 Jun 2022 at 16:22, simwangrui ***@***.***> wrote:

> Hi,
> I only merge DescriptorSet changes,so it still support
> VK_LAYER_LUNARG_standard_validation,and it now work perfect without any
> error.Thinks a lot.
>
VK_LAYER_LUNARG_standard_validation is been deprecated for a couple of
years, are you finding it's replacement VK_LAYER_KHRONOS_validation isn't
sufficient on your driver?

**Comment by simwangrui** [comment] 2022-06-27 03:46
Hi,
I was learning  Vulkan and VSG from the beginning,not noticed replacement of the VK_LAYER_LUNARG_standard_validation.I will using VK_LAYER_KHRONOS_validation in the future.Thank you very much for your information。
Best wishes

**Comment by simwangrui** [comment] 2022-06-27 03:46
Hi,
I was learning  Vulkan and VSG from the beginning,not noticed replacement of the VK_LAYER_LUNARG_standard_validation.I will using VK_LAYER_KHRONOS_validation in the future.Thank you very much for your information。
Best wishes
